### ISSUE TITLE
LOADING state doesn't work well with redis-py BusyLoadingError

### ISSUE THREAD

**Issue by safa-topal** [dragonflydb/dragonfly#2617] opened 2024-02-19 15:28 UTC
**Describe the bug**
When `ping` command is executed against a DF instance that's in LOADING state, redis-py throws `ResponseError` with message `Can not execute during LOADING` however when same state happens with Redis server, it throws `BusyLoadingError`

**To Reproduce**
1. Ensure a DF server is in LOADING state
2. Then make ping request with `redis-py` to DF server
3. redis-py throws `ResponseError`

**Expected behavior**
When `ping` cmd si executed against DF, `redis-py` should throw `BusyLoadingError`

**Environment (please complete the following information):**
OS: Fedora 38
Kernel: 6.3.12-200.fc38.x86_64
Containerized?: toolbox
Dragonfly Version: 1.14.3

**Comment by kostasrim** [comment] 2024-02-19 15:42
Hi @safa-topal how are you?

So just to confirm, the issue is the response type during loading correct ? I will take a look and ping here.

**Comment by safa-topal** [comment] 2024-02-19 16:01
@kostasrim hello! All good, and how are you? Hope all is well.

> So just to confirm, the issue is the response type during loading && issuing a PING command correct ? I will take a look and ping here.

Yes, this is the case I am hitting, it is ideal for us if it returns `BusyLoadingError` on this case at least.

**Comment by dranikpg** [comment] 2024-02-19 16:02
@kostasrim 

This is something we know about. The issue is that we use the generic error code `-ERR ...` for reporting this error, whereas the client expects `-LOADING ... `  to correctly parse it into a predefined exception class

We should go over this list, I see some other codes there that we might miss and use -Err instead
https://github.com/redis/redis-py/blob/ebb6171832f284d61df4fe3afa0a23af88fbf9b6/redis/_parsers/base.py#L14

**Comment by kostasrim** [comment] 2024-02-19 16:05
@safa-topal sounds good:) 

@dranikpg I figured we would need to change this in other places as well. Thank you for the reply, I will get to it later today

**Comment by romange** [comment] 2024-02-19 18:27
@dranikpg  is it new? I was under the impression that when Dragonfly project started (redis 6.x era), it responded with `-ERR` for most errors. Am I wrong?

**Comment by safa-topal** [comment] 2024-02-20 08:30
Thanks for responses. Is this something I can expect a fix soon on 1.14 or later versions?

**Comment by romange** [comment] 2024-02-20 09:32
it should be fixed for 1.15 @kostasrim FYI

**Comment by kostasrim** [comment] 2024-02-20 11:38
done. @dranikpg I opened #2630 for the rest cases to improve compatibility with redis

**Comment by romange** [comment] 2024-02-20 16:46
fixed in v1.14.4

**Closed by romange** 2024-02-20 16:46 UTC
Labels: bug
