### ISSUE TITLE
Fedora 38 build error on main branch 

### ISSUE THREAD

**Issue by zamazan4ik** [dragonflydb/dragonfly#1504] opened 2023-07-02 01:48 UTC
**Describe the bug**
DragonflyDB build fails on Fedora 38.

**To Reproduce**
1. Checkout DragonflyDB source.
2. `CC=clang CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/zamazan4ik/open_source/install_dragon_release -G Ninja ../dragonfly`
3. `ninja dragonfly`
4. See the error

Error test:

> [101/101] Linking CXX executable dragonfly
> FAILED: dragonfly 
> : && /usr/lib64/ccache/clang++ -Wall -Wextra -g -fPIC -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer -Wno-unused-parameter -march=sandybridge -mtune=skylake  -std=c++20 -DHAS_RAWMEMCHR -fcolor-diagnostics -Wno-deprecated-copy  -O3 -DNDEBUG  src/server/CMakeFiles/dragonfly.dir/dfly_main.cc.o -o dragonfly  lib/libbase.a  lib/libdragonfly_lib.a  lib/libdfly_transaction.a  lib/libdfly_core.a  lib/libquery_parser.a  third_party/libs/reflex/lib/libreflex.a  lib/liblua_modules.a  third_party/libs/lua/lib/liblua.a  lib/libdfly_facade.a  lib/libhttp_server_lib.a  lib/libmetrics.a  third_party/libs/gperf/lib/libprofiler.a  -lunwind  third_party/libs/dconv/lib/libdouble-conversion.a  lib/libredis_lib.a  third_party/libs/mimalloc/lib/libmimalloc.a  lib/libaws_lib.a  /usr/lib64/libxml2.so  lib/libstrings_lib.a  lib/libhtml_lib.a  lib/libhttp_client_lib.a  lib/libtls_lib.a  lib/libfibers2.a  lib/libio.a  third_party/libs/uring/lib/liburing.a  /usr/lib64/libboost_context.so.1.78.0  third_party/libs/cares/lib/libcares.a  /usr/lib64/libssl.so  /usr/lib64/libcrypto.so  lib/libhttp_utils.a  lib/libbase.a  _deps/glog-build/libglog.a  /usr/lib64/libunwind.so  _deps/abseil_cpp-build/absl/flags/libabsl_flags_parse.a  _deps/abseil_cpp-build/absl/flags/libabsl_flags_usage.a  _deps/abseil_cpp-build/absl/flags/libabsl_flags_usage_internal.a  _deps/abseil_cpp-build/absl/flags/libabsl_flags.a  _deps/abseil_cpp-build/absl/flags/libabsl_flags_internal.a  _deps/abseil_cpp-build/absl/flags/libabsl_flags_marshalling.a  _deps/abseil_cpp-build/absl/strings/libabsl_str_format_internal.a  _deps/abseil_cpp-build/absl/flags/libabsl_flags_reflection.a  _deps/abseil_cpp-build/absl/flags/libabsl_flags_config.a  _deps/abseil_cpp-build/absl/flags/libabsl_flags_program_name.a  _deps/abseil_cpp-build/absl/flags/libabsl_flags_private_handle_accessor.a  _deps/abseil_cpp-build/absl/flags/libabsl_flags_commandlineflag.a  _deps/abseil_cpp-build/absl/flags/libabsl_flags_commandlineflag_internal.a  _deps/abseil_cpp-build/absl/strings/libabsl_cord.a  _deps/abseil_cpp-build/absl/strings/libabsl_cordz_info.a  _deps/abseil_cpp-build/absl/strings/libabsl_cord_internal.a  _deps/abseil_cpp-build/absl/strings/libabsl_cordz_functions.a  _deps/abseil_cpp-build/absl/strings/libabsl_cordz_handle.a  _deps/abseil_cpp-build/absl/crc/libabsl_crc_cord_state.a  _deps/abseil_cpp-build/absl/crc/libabsl_crc32c.a  _deps/abseil_cpp-build/absl/crc/libabsl_crc_internal.a  _deps/abseil_cpp-build/absl/crc/libabsl_crc_cpu_detect.a  _deps/abseil_cpp-build/absl/hash/libabsl_hash.a  _deps/abseil_cpp-build/absl/hash/libabsl_city.a  _deps/abseil_cpp-build/absl/types/libabsl_bad_variant_access.a  _deps/abseil_cpp-build/absl/hash/libabsl_low_level_hash.a  _deps/abseil_cpp-build/absl/container/libabsl_raw_hash_set.a  _deps/abseil_cpp-build/absl/container/libabsl_hashtablez_sampler.a  _deps/abseil_cpp-build/absl/profiling/libabsl_exponential_biased.a  _deps/abseil_cpp-build/absl/synchronization/libabsl_synchronization.a  _deps/abseil_cpp-build/absl/synchronization/libabsl_graphcycles_internal.a  -lrt  _deps/abseil_cpp-build/absl/time/libabsl_time.a  _deps/abseil_cpp-build/absl/time/libabsl_civil_time.a  _deps/abseil_cpp-build/absl/time/libabsl_time_zone.a  _deps/abseil_cpp-build/absl/debugging/libabsl_failure_signal_handler.a  _deps/abseil_cpp-build/absl/debugging/libabsl_examine_stack.a  _deps/abseil_cpp-build/absl/debugging/libabsl_symbolize.a  _deps/abseil_cpp-build/absl/debugging/libabsl_demangle_internal.a  _deps/abseil_cpp-build/absl/base/libabsl_malloc_internal.a  _deps/abseil_cpp-build/absl/debugging/libabsl_stacktrace.a  _deps/abseil_cpp-build/absl/debugging/libabsl_debugging_internal.a  third_party/libs/xxhash/lib/libxxhash.a  lib/libhttp_beast_prebuilt.a  /usr/lib64/libboost_system.so.1.78.0  _deps/abseil_cpp-build/absl/random/libabsl_random_distributions.a  _deps/abseil_cpp-build/absl/random/libabsl_random_seed_sequences.a  _deps/abseil_cpp-build/absl/random/libabsl_random_internal_pool_urbg.a  _deps/abseil_cpp-build/absl/random/libabsl_random_internal_randen.a  _deps/abseil_cpp-build/absl/random/libabsl_random_internal_randen_hwaes.a  _deps/abseil_cpp-build/absl/random/libabsl_random_internal_randen_hwaes_impl.a  _deps/abseil_cpp-build/absl/random/libabsl_random_internal_randen_slow.a  _deps/abseil_cpp-build/absl/random/libabsl_random_internal_platform.a  _deps/abseil_cpp-build/absl/random/libabsl_random_internal_seed_material.a  _deps/abseil_cpp-build/absl/strings/libabsl_strings.a  _deps/abseil_cpp-build/absl/strings/libabsl_strings_internal.a  _deps/abseil_cpp-build/absl/base/libabsl_base.a  _deps/abseil_cpp-build/absl/base/libabsl_spinlock_wait.a  -lrt  _deps/abseil_cpp-build/absl/numeric/libabsl_int128.a  _deps/abseil_cpp-build/absl/types/libabsl_bad_optional_access.a  _deps/abseil_cpp-build/absl/base/libabsl_throw_delegate.a  _deps/abseil_cpp-build/absl/base/libabsl_raw_logging_internal.a  _deps/abseil_cpp-build/absl/base/libabsl_log_severity.a  _deps/abseil_cpp-build/absl/random/libabsl_random_seed_gen_exception.a  -lzstd  third_party/libs/lz4/lib/liblz4.a && :
> clang-16: error: no such file or directory: 'third_party/libs/cares/lib/libcares.a'

**Expected behavior**
DragonflyDB builds successfully.

**Environment (please complete the following information):**
 - OS: Fedora 38
 - Kernel: 6.3.7
 - Dragonfly Version: main branch on `54fbf0d6fcecc814abd61515b4eacb5064263447`

**Comment by zamazan4ik** [comment] 2023-07-02 01:52
On 1.4.0 tag build fails with the following error (all flags/commands are the same as above):

> [4/7] Building CXX object src/server/CMakeFiles/dragonfly.dir/dfly_main.cc.o
> FAILED: src/server/CMakeFiles/dragonfly.dir/dfly_main.cc.o 
> /usr/lib64/ccache/clang++ -DBOOST_ASIO_SEPARATE_COMPILATION -DBOOST_BEAST_SEPARATE_COMPILATION -DBOOST_CONTEXT_DYN_LINK -DBOOST_CONTEXT_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DGLOG_CUSTOM_PREFIX_SUPPORT -DUSE_FB2 -DUSE_ZMALLOC_MI -DSOURCE_PATH_FROM_BUILD_ENV=/home/zamazan4ik/open_source/dragonfly -I/home/zamazan4ik/open_source/dragonfly -I/home/zamazan4ik/open_source/dragonfly/genfiles -I/home/zamazan4ik/open_source/dragonfly/src -I/home/zamazan4ik/open_source/dragonfly/helio -I/home/zamazan4ik/open_source/dragonfly/genfiles/src -I/home/zamazan4ik/open_source/build_dragon_release/_deps/glog-build -I/home/zamazan4ik/open_source/build_dragon_release/_deps/glog-src/src -I/home/zamazan4ik/open_source/build_dragon_release/_deps/abseil_cpp-src -isystem /home/zamazan4ik/open_source/build_dragon_release/third_party/libs/xxhash/include -isystem /home/zamazan4ik/open_source/build_dragon_release/third_party/libs/reflex/include -isystem /home/zamazan4ik/open_source/build_dragon_release/third_party/libs/mimalloc/include -isystem /home/zamazan4ik/open_source/build_dragon_release/third_party/libs/lua/include -isystem /home/zamazan4ik/open_source/build_dragon_release/third_party/libs/uring/include -isystem /home/zamazan4ik/open_source/build_dragon_release/third_party/libs/cares/include -isystem /home/zamazan4ik/open_source/build_dragon_release/third_party/libs/jsoncons/include -isystem /home/zamazan4ik/open_source/build_dragon_release/third_party/libs/gperf/include -isystem /home/zamazan4ik/open_source/build_dragon_release/third_party/libs/dconv/include -isystem /usr/include/libxml2 -isystem /home/zamazan4ik/open_source/build_dragon_release/third_party/libs/rapidjson/include -isystem /home/zamazan4ik/open_source/build_dragon_release/third_party/libs/lz4/include -Wall -Wextra -g -fPIC -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer -Wno-unused-parameter -march=sandybridge -mtune=skylake  -std=c++20 -DHAS_RAWMEMCHR -fcolor-diagnostics -Wno-deprecated-copy  -O3 -DNDEBUG -std=gnu++17 -march=core2 -MD -MT src/server/CMakeFiles/dragonfly.dir/dfly_main.cc.o -MF src/server/CMakeFiles/dragonfly.dir/dfly_main.cc.o.d -o src/server/CMakeFiles/dragonfly.dir/dfly_main.cc.o -c /home/zamazan4ik/open_source/dragonfly/src/server/dfly_main.cc
> /home/zamazan4ik/open_source/dragonfly/src/server/dfly_main.cc:332:77: error: too few arguments to function call, expected 3, have 2
>     error_code ec = acceptor->AddUDSListener(unix_sock.c_str(), uds_listener);
>                     ~~~~~~~~~~~~~~~~~~~~~~~~                                ^
> /home/zamazan4ik/open_source/dragonfly/helio/util/accept_server.h:43:19: note: 'AddUDSListener' declared here
>   std::error_code AddUDSListener(const char* path, mode_t permissions, ListenerInterface* listener);
>                   ^
> 1 error generated.

**Comment by zamazan4ik** [comment] 2023-07-02 01:54
On 1.3.0 tag build fails with the following errors:

**Comment by zamazan4ik** [comment] 2023-07-02 02:00
Switching to GCC 13.1.1 does not help - I get the same errors as on Clang (tested on `main` and `1.4.0` branches).

**Comment by chakaz** [comment] 2023-07-02 07:18
Hi @zamazan4ik , thanks for reporting this.
Let's start from the first comment and see what went wrong with building c-ares. c-ares is a C library that does DNS resolving async, and is one of Dragonfly's dependencies.
Can you please paste here, from the build logs, the relevant parts for that?
In case you can't find it, it might be useful to do:
```
cd <dragonfly-build-dir>
cd third_party/cares
mkdir build
cmake ..
make
```
Does that build with no issues?

**Comment by royjacobson** [comment] 2023-07-02 07:59
I actually know this issue, the problem is that for some reason the library is built into `lib64`, not `lib`.

I just copied it manually to the other path as a workaround, but yeah it would be great to fix it :)

**Comment by chakaz** [comment] 2023-07-02 08:00
@royjacobson on which setups does this happen to you? Also on Fedora?

**Comment by royjacobson** [comment] 2023-07-02 08:17
> @royjacobson on which setups does this happen to you? Also on Fedora?

Yep

**Comment by zamazan4ik** [comment] 2023-07-02 12:35
@chakaz do you still need a repro from my side? As far as I see, you already found the root cause and the fix is sent.

**Comment by chakaz** [comment] 2023-07-02 12:51
Yes, that's right, no need for any action on your side.
If you want though, you could patch in https://github.com/romange/helio/pull/91 (note that it's in the sub repo 'helio') and see if it works for you

**Closed** 2023-07-02 17:23 UTC
Labels: bug
