### ISSUE TITLE
High CPU after suspending systems

### ISSUE THREAD

**Issue by mostafaqanbaryan** [dragonflydb/dragonfly#1705] opened 2023-08-16 05:17 UTC
**Describe the bug**
We have multiple development environment. Since the day we moved from Redis to Dragonfly (about 2 weeks now), everything works  great.
But the single problem that we have with Dragonfly is that, when we put are systems to sleep at night and comeback the next morning, all our CPUs are full and nothing works anymore.
After restarting Dragonfly containers, everything would be back to normal.
I don't know if it has something to do with `save_schedule` or not.

**To Reproduce**
1. Bring up a Dragonfly container (we have two, of course)
2. Put the system to sleep for a few hours (maybe less?)
3. After that, CPUs should be at their 100%

**Expected behavior**
After sleep, things should be normal.

**Environment (please complete the following information):**
 - OS: PopOS
 - Kernel: 6.4.6
 - Containerized: Docker Compose
 - Dragonfly Version: 1.6.2

**Reproducible Code Snippet**
In docker-compose.yml, set the command as below:
```
dragonfly --hz 1 --logtostderr --save_schedule '*:00' --maxmemory=3gb --cache_mode=true --dbfilename dump.rdb --nodf_snapshot_format"
```

**Comment by romange** [comment] 2023-08-16 12:21
Hi @mostafaqanbaryan thanks for reporting! However this info is not enought for us to reproduce the problem. 
Can you please explain what does it mean that you put systems to sleep?  
Can you help us to narrow the search for root cause by removing "--save_schedule" flag and checking if it solves the problem?

**Comment by mostafaqanbaryan** [comment] 2023-08-19 07:13
Hi,
Sorry for replying a few days later.
Yes, of course.
What I meant was when we suspend our systems (`systemctl suspend` or via GUI).
I will test your solution tonight and report the result tomorrow.
Thank you.

**Comment by mostafaqanbaryan** [comment] 2023-08-20 04:27
Nope, removing `save_schedule` didn't fix it.
![image](https://github.com/dragonflydb/dragonfly/assets/94293456/d1923ba1-fa62-4af9-9bba-2ab676997869)

**Comment by romange** [comment] 2023-08-21 05:02
thanks, I succeeded to reproduce it. For the reference, the problem is in helio library that relies on cpu cycle counter in some place  and apparently cycle counters are reset upon suspend.
this will be fixed in the next release.

**Comment by mostafaqanbaryan** [comment] 2023-08-21 05:18
Thank you!

**Closed** 2023-09-19 08:08 UTC
Labels: bug
