### ISSUE TITLE
replication: data loss after a replica is being marked as master

### ISSUE THREAD

**Issue by Pothulapati** [dragonflydb/dragonfly#1082] opened 2023-04-13 06:08 UTC
**Describe the bug**

With the new [dragonfly-operator](https://github.com/dragonflydb/dragonfly-operator), There are some instances where after a replica is marked as the new
master, It gets stuck on loading for a bit, and then ends up loosing data which we don't want.

**To Reproduce**

Run the Operator following the readme, and then keep deleting the master and see
that the data is lost.

**Logs**

Was able to replica this issue across multiple instances, and here are
the logs in each case (some with more/less verbosity):
- https://gist.github.com/Pothulapati/753011fbe9052f4eacf46ae7fa8b1184
- https://gist.github.com/Pothulapati/b70afbb8957a206cb82f7ae23de30faf
- https://gist.github.com/Pothulapati/2e1ad2319a91cc8fe61d909e3162ca4e
- https://gist.github.com/Pothulapati/78e15905e8f834efc86b4b61314c9bb0

**Comment by romange** [comment] 2023-04-13 06:13
Thanks! Can you please expand how you recognize data loss?
Could it be due to eventually consistent behavior? i.e. only the last, in-flight updates are lost?

**Comment by Pothulapati** [comment] 2023-04-13 06:30
> Thanks! Can you please expand how you recognise data loss?

I've did some data insertions, and was not able to retrieve them after the pod was elected as the new master. Considering it was manual insertion, I was expecting the replication should work asap. Is there a time frequency at which replication happens? Also, I did wait a bit btw data insertions, and the replica being marked as the new master.

**Comment by romange** [comment] 2023-04-13 07:09
yes, it should replicate fast.

What would help is a more detailed description of the state of affairs:
1. before you kill a master - can you connect to the pod directly and fetch its state (INFO ALL)?
2. after you kill a master and a new pod is elected - can you paste here "INFO ALL" ? 

i.e. are all key missing? just some? Did it replicate and then data was lost or it has never been replicated? 
This may help with finding a root cause.

**Comment by Pothulapati** [comment] 2023-04-13 08:49
<details>
<summary>`INFO ALL` on the master before getting killed </summary>




```
dragonfly-sample.default:6379> INFO ALL
# Server
redis_version:6.2.11
dfly_version:df-v1.1.2
redis_mode:standalone
arch_bits:64
multiplexing_api:iouring
tcp_port:6379
uptime_in_seconds:1964
uptime_in_days:0

# Clients
connected_clients:27
client_read_buf_capacity:6912
blocked_clients:0

# Memory
used_memory:3380168
used_memory_human:3.22MiB
used_memory_peak:3380168
comitted_memory:186744832
used_memory_rss:156831744
used_memory_rss_human:149.57MiB
object_used_memory:0
table_used_memory:3100944
num_buckets:73920
num_entries:1
inline_keys:0
strval_bytes:0
updateval_amount:0
listpack_blobs:0
listpack_bytes:0
small_string_bytes:0
pipeline_cache_bytes:0
maxmemory:18325261516
maxmemory_human:17.07GiB
cache_mode:store
maxmemory_policy:noeviction

# Stats
total_connections_received:418
total_commands_processed:434
instantaneous_ops_per_sec:0
total_pipelined_commands:0
total_net_input_bytes:463
total_net_output_bytes:15663
instantaneous_input_kbps:-1
instantaneous_output_kbps:-1
rejected_connections:-1
expired_keys:0
evicted_keys:0
hard_evictions:0
garbage_checked:0
garbage_collected:0
bump_ups:0
stash_unloaded:0
traverse_ttl_sec:0
delete_ttl_sec:0
keyspace_hits:0
keyspace_misses:1
total_reads_processed:16
total_writes_processed:2363
async_writes_count:0
parser_err_count:0
defrag_attempt_total:0
defrag_realloc_total:0
defrag_task_invocation_total:0

# TIERED
tiered_entries:0
tiered_bytes:0
tiered_reads:0
tiered_writes:0
tiered_reserved:0
tiered_capacity:0
tiered_aborted_write_total:0
tiered_flush_skip_total:0

# PERSISTENCE
last_save:1681373151
last_save_duration_sec:0
last_save_file:

# Replication
role:master
connected_slaves:2
slave0:ip=10.244.0.14,port=6379
slave1:ip=10.244.0.15,port=6379
master_replid:695f51e247db5a59f035fb443597e17c96a0f230

# Commandstats
cmd_COMMAND:2
cmd_DFLY:28
cmd_GET:1
cmd_INFO:1
cmd_PING:392
cmd_REPLCONF:8
cmd_SET:1
cmd_SLAVEOF:1

# Errorstats
syntax_error:1

# Keyspace
db0:keys=1,expires=0,avg_ttl=-1

# CPU
used_cpu_sys:169.38577
used_cpu_user:67.122747
used_cpu_sys_children:0.1305
used_cpu_user_children:0.20157
used_cpu_sys_main_thread:15.259148
used_cpu_user_main_thread:5.802834

# Cluster
cluster_enabled:0
```
</details>

<details>
<summary>
`INFO ALL` on the replica before the master was deleted
</summary>

```
If you don't see a command prompt, try pressing enter.
10.244.0.14:6379> INFO ALL
# Server
redis_version:6.2.11
dfly_version:df-v1.1.2
redis_mode:standalone
arch_bits:64
multiplexing_api:iouring
tcp_port:6379
uptime_in_seconds:2028
uptime_in_days:0

# Clients
connected_clients:1
client_read_buf_capacity:256
blocked_clients:0

# Memory
used_memory:3380168
used_memory_human:3.22MiB
used_memory_peak:3380168
comitted_memory:186875904
used_memory_rss:161054720
used_memory_rss_human:153.59MiB
object_used_memory:0
table_used_memory:3100944
num_buckets:73920
num_entries:1
inline_keys:0
strval_bytes:0
updateval_amount:0
listpack_blobs:0
listpack_bytes:0
small_string_bytes:0
pipeline_cache_bytes:0
maxmemory:18208240435
maxmemory_human:16.96GiB
cache_mode:store
maxmemory_policy:noeviction

# Stats
total_connections_received:413
total_commands_processed:418
instantaneous_ops_per_sec:0
total_pipelined_commands:0
total_net_input_bytes:40
total_net_output_bytes:15395
instantaneous_input_kbps:-1
instantaneous_output_kbps:-1
rejected_connections:-1
expired_keys:0
evicted_keys:0
hard_evictions:0
garbage_checked:0
garbage_collected:0
bump_ups:0
stash_unloaded:0
traverse_ttl_sec:0
delete_ttl_sec:0
keyspace_hits:0
keyspace_misses:0
total_reads_processed:2
total_writes_processed:2290
async_writes_count:0
parser_err_count:0
defrag_attempt_total:0
defrag_realloc_total:0
defrag_task_invocation_total:0

# TIERED
tiered_entries:0
tiered_bytes:0
tiered_reads:0
tiered_writes:0
tiered_reserved:0
tiered_capacity:0
tiered_aborted_write_total:0
tiered_flush_skip_total:0

# PERSISTENCE
last_save:1681373173
last_save_duration_sec:0
last_save_file:

# Replication
role:replica
master_host:10.244.0.13
master_port:6379
master_link_status:up
master_last_io_seconds_ago:89
master_sync_in_progress:0

# Commandstats
cmd_COMMAND:2
cmd_FLUSHALL:1
cmd_INFO:8
cmd_PING:404
cmd_SELECT:1
cmd_SET:1
cmd_SLAVEOF:1

# Errorstats
syntax_error:1

# Keyspace
db0:keys=1,expires=0,avg_ttl=-1

# CPU
used_cpu_sys:173.954115
used_cpu_user:64.786544
used_cpu_sys_children:0.373
used_cpu_user_children:0.19797
used_cpu_sys_main_thread:15.591361
used_cpu_user_main_thread:5.551535

# Cluster
cluster_enabled:0
```

</details>

<details>
<summary> INFO ALL on the newly elected master during its `LOADING` state </summary>

```
dragonfly-sample.default:6379> INFO ALL
# Server
redis_version:6.2.11
dfly_version:df-v1.1.2
redis_mode:standalone
arch_bits:64
multiplexing_api:iouring
tcp_port:6379
uptime_in_seconds:2124
uptime_in_days:0

# Clients
connected_clients:11
client_read_buf_capacity:2816
blocked_clients:0

# Memory
used_memory:3380168
used_memory_human:3.22MiB
used_memory_peak:3380168
comitted_memory:197230592
used_memory_rss:163053568
used_memory_rss_human:155.50MiB
object_used_memory:0
table_used_memory:3100944
num_buckets:73920
num_entries:0
inline_keys:0
strval_bytes:0
updateval_amount:0
listpack_blobs:0
listpack_bytes:0
small_string_bytes:0
pipeline_cache_bytes:0
maxmemory:18208240435
maxmemory_human:16.96GiB
cache_mode:store
maxmemory_policy:noeviction

# Stats
total_connections_received:484
total_commands_processed:507
instantaneous_ops_per_sec:7
total_pipelined_commands:0
total_net_input_bytes:518
total_net_output_bytes:20175
instantaneous_input_kbps:-1
instantaneous_output_kbps:-1
rejected_connections:-1
expired_keys:0
evicted_keys:0
hard_evictions:0
garbage_checked:0
garbage_collected:0
bump_ups:0
stash_unloaded:0
traverse_ttl_sec:0
delete_ttl_sec:0
keyspace_hits:1
keyspace_misses:0
total_reads_processed:19
total_writes_processed:2407
async_writes_count:0
parser_err_count:0
defrag_attempt_total:0
defrag_realloc_total:0
defrag_task_invocation_total:0

# TIERED
tiered_entries:0
tiered_bytes:0
tiered_reads:0
tiered_writes:0
tiered_reserved:0
tiered_capacity:0
tiered_aborted_write_total:0
tiered_flush_skip_total:0

# PERSISTENCE
last_save:1681373173
last_save_duration_sec:0
last_save_file:

# Replication
role:replica
master_host:10.244.0.13
master_port:6379
master_link_status:down
master_last_io_seconds_ago:1681375297
master_sync_in_progress:0

# Commandstats
cmd_COMMAND:2
cmd_DFLY:14
cmd_FLUSHALL:2
cmd_GET:1
cmd_INFO:10
cmd_PING:424
cmd_REPLCONF:8
cmd_SELECT:1
cmd_SET:1
cmd_SLAVEOF:5

# Errorstats
Can not execute during LOADING:39
syntax_error:1

# Keyspace
db0:keys=0,expires=0,avg_ttl=-1

# CPU
used_cpu_sys:180.680355
used_cpu_user:67.71761
used_cpu_sys_children:0.373
used_cpu_user_children:0.19797
used_cpu_sys_main_thread:0.20147
used_cpu_user_main_thread:0.0

# Cluster
cluster_enabled:0
```
 </details>
 
 <details>
 <summary> INFO ALL on the new master after its accepting requests and data is lost </summary>

 ```
dragonfly-sample.default:6379> GET 1
(nil)
dragonfly-sample.default:6379> INFO ALL
# Server
redis_version:6.2.11
dfly_version:df-v1.1.2
redis_mode:standalone
arch_bits:64
multiplexing_api:iouring
tcp_port:6379
uptime_in_seconds:2496
uptime_in_days:0

# Clients
connected_clients:27
client_read_buf_capacity:6912
blocked_clients:0

# Memory
used_memory:3380168
used_memory_human:3.22MiB
used_memory_peak:3380168
comitted_memory:197230592
used_memory_rss:163053568
used_memory_rss_human:155.50MiB
object_used_memory:0
table_used_memory:3100944
num_buckets:73920
num_entries:0
inline_keys:0
strval_bytes:0
updateval_amount:0
listpack_blobs:0
listpack_bytes:0
small_string_bytes:0
pipeline_cache_bytes:0
maxmemory:18208240435
maxmemory_human:16.96GiB
cache_mode:store
maxmemory_policy:noeviction

# Stats
total_connections_received:856
total_commands_processed:903
instantaneous_ops_per_sec:0
total_pipelined_commands:0
total_net_input_bytes:1143
total_net_output_bytes:40288
instantaneous_input_kbps:-1
instantaneous_output_kbps:-1
rejected_connections:-1
expired_keys:0
evicted_keys:0
hard_evictions:0
garbage_checked:0
garbage_collected:0
bump_ups:0
stash_unloaded:0
traverse_ttl_sec:0
delete_ttl_sec:0
keyspace_hits:1
keyspace_misses:3
total_reads_processed:43
total_writes_processed:2858
async_writes_count:0
parser_err_count:0
defrag_attempt_total:0
defrag_realloc_total:0
defrag_task_invocation_total:0

# TIERED
tiered_entries:0
tiered_bytes:0
tiered_reads:0
tiered_writes:0
tiered_reserved:0
tiered_capacity:0
tiered_aborted_write_total:0
tiered_flush_skip_total:0

# PERSISTENCE
last_save:1681373173
last_save_duration_sec:0
last_save_file:

# Replication
role:master
connected_slaves:2
slave0:ip=10.244.0.15,port=6379
slave1:ip=10.244.0.20,port=6379
master_replid:5c4b0db621c5d796a0531e275a5123327b16801e

# Commandstats
cmd_COMMAND:2
cmd_DFLY:42
cmd_FLUSHALL:2
cmd_GET:4
cmd_INFO:13
cmd_PING:474
cmd_REPLCONF:16
cmd_SELECT:1
cmd_SET:1
cmd_SLAVEOF:5

# Errorstats
Can not execute during LOADING:343
could not connect to master: Connection timed out:1
syntax_error:1

# Keyspace
db0:keys=0,expires=0,avg_ttl=-1

# CPU
used_cpu_sys:208.69841
used_cpu_user:76.637855
used_cpu_sys_children:0.373
used_cpu_user_children:0.19797
used_cpu_sys_main_thread:0.36454
used_cpu_user_main_thread:0.0

# Cluster
cluster_enabled:0
 ```
</details>


Data in this case was a plain `SET 1 2`, and `GET 1`.

**Comment by Pothulapati** [comment] 2023-04-13 09:59
Hmmm 🤔 Happy to give you any additional info you might want.

One other important thing with the Operator is that the when the Operator tries to mark a replica as a master, and does not get a `OK` response (due to timout, etc), It keeps retrying the same command every 5 seconds. Do you think this might cause any bugs? 🤔

**Comment by adiholden** [comment] 2023-04-19 11:09
@Pothulapati can I close this one?

**Comment by Pothulapati** [comment] 2023-04-19 11:17
Yep, I think let's close this for now as we are not able to repro this, and multiple fixes landed in the operator that makes sure to choose only a running replica. (We missed this in some cases)

I will reopen it if this happens again.

**Closed** 2023-04-19 11:17 UTC
Labels: bug
