### ISSUE TITLE
Incompatibility with Cashews Python Caching Library - "Subcommand ID not supported" Error

### ISSUE THREAD

**Issue by TweedBeetle** [dragonflydb/dragonfly#3666] opened 2024-09-06 19:38 UTC
### Description

When using Dragonfly as a drop-in replacement for Redis with the Cashews Python caching library, I'm encountering errors both in my Python application and in the Dragonfly container logs.

#### Python Application Error:

```
ERROR:cashews.backends.redis.client_side:redis client side: can not start listen task
```

#### Dragonfly Container Logs:

```
E20240906 19:27:24.971956    12 server_family.cc:1771] Subcommand ID not supported
```

### Environment:

- Dragonfly version: df-v1.22.0-67117ff081b60f28a49c4c5db383a62953f71f3e
- Operating System: Sonoma 14.6.1 (23G93)

### Steps to Reproduce:

1. Set up Dragonfly in a Docker container
2. Install Cashews Python caching library
3. Configure Cashews to use Dragonfly as the backend
4. Attempt to use Cashews for caching operations in a Python application

### Expected Behavior:

Dragonfly should work as a drop-in replacement for Redis, allowing Cashews to perform caching operations without errors.

### Actual Behavior:

- The Python application fails to start the listen task for Redis client-side operations.
- Dragonfly logs show repeated "Subcommand ID not supported" errors.

### Additional Context:

This issue suggests that there might be some Redis commands or subcommands that Cashews is using which are not currently supported by Dragonfly. It would be helpful to identify these specific commands to either implement them in Dragonfly or find a workaround in Cashews.

### Possible Solutions:

1. Implement support for the missing subcommands in Dragonfly.
2. Provide detailed documentation on any Redis commands not supported by Dragonfly, especially those commonly used by caching libraries.
3. Consider adding a compatibility mode that gracefully handles unsupported commands without throwing errors.

Thank you for your attention to this issue. Let me know if you need any additional information or clarification.

**Comment by BorysTheDev** [comment] 2024-09-07 06:39
It looks that missing command is CLIENT ID.

**Comment by romange** [comment] 2024-09-07 09:21
yes, it's duplicate of #3651

**Comment by adiholden** [comment] 2024-09-26 06:13
client id command was added to dfly version 1.23.0
closing this issue now.
@TweedBeetle please let us know if you experience any other issue while using the Cashews Python library. Thank you

**Closed by adiholden** 2024-09-26 06:14 UTC
Labels: bug

**Comment by TweedBeetle** [comment] 2024-09-26 06:50
Thank you, I appreciate it!
