### ISSUE TITLE
rate-limiter-flexible don't work since 1.11

### ISSUE THREAD

**Issue by yovanoc** [dragonflydb/dragonfly#2034] opened 2023-10-17 13:42 UTC
Probably because of this: https://github.com/animir/node-rate-limiter-flexible/blob/846b5a28987f28e0e13b5ec7965def4aa39a22ab/lib/RateLimiterRedis.js#L4

when I log the .consume response it gives me big msBeforeNext

```
RateLimiterRes {
  _remainingPoints: 4991,
  _msBeforeNext: 281476674260404640,
  _consumedPoints: 9,
  _isFirstInDuration: false
}
```

dragonfly regression or was working before but an issue in the rate-limiter package ?

**Comment by yovanoc** [comment] 2023-10-17 14:45
I can't right now but will try to do that later

**Comment by yovanoc** [comment] 2023-10-19 15:47
Sorry for the delay.

https://github.com/yovanoc/df-repro

**Comment by chakaz** [comment] 2023-10-26 20:07
Interesting!
It seems like, for some reason, expiration setting via Lua doesn't work as intended. I'm looking into this.

**Comment by chakaz** [comment] 2023-10-26 20:45
Thanks @yovanoc for the interesting bug report, this is indeed a regression.
It should be fixed with https://github.com/dragonflydb/dragonfly/pull/2080

**Comment by yovanoc** [comment] 2023-10-26 20:48
oh nice! glad to help as I can

**Closed** 2023-10-27 10:13 UTC
Labels: bug

**Comment by yovanoc** [comment] 2023-10-28 15:33
happy to see this merged, but where can we see your push to prod routine, I see you have dragonfly, help-dragonfly, and dragonfly-weekly, where its explained your releases process? thanks

**Comment by chakaz** [comment] 2023-10-28 18:33
We release new versions every few weeks, you can follow our announcements on GitHub / Discord.

**Comment by yovanoc** [comment] 2023-10-28 21:29
Yeah but actually If I understand correctly the k8s operator package it's still in 1.10 so I just wanted to know the pattern you follow between your packages

**Comment by chakaz** [comment] 2023-10-29 06:53
Indeed, the operator still uses 1.10. We'll update it this week.
We manually update the operator to the next release a week or so after the binary release in case there are issues we did not catch in the release.

**Comment by romange** [comment] 2023-10-29 07:52
We do not bundle k8s operator and Dragonfly releases. But you can always override the`image` parameter and specify the version you want.

**Comment by yovanoc** [comment] 2023-11-07 20:06
this issue still there in 1.12.1

**Comment by chakaz** [comment] 2023-11-07 20:12
@yovanoc I just tried locally, by downloading the latest version, and I cannot reproduce this issue.
How do you run Dragonfly? Can you show the output of `dragonfly --version`, and the output of your repro script (i.e. `npm run start`)?

**Comment by yovanoc** [comment] 2023-11-07 20:13
My bad I had to delete all the old keys.. because there was still there with these long expirations

**Comment by chakaz** [comment] 2023-11-07 20:15
Ah, that makes sense :)
