### ISSUE TITLE
Maxmemory isn't enforced in DEBUG POPULATE 

### ISSUE THREAD

**Issue by eliskovets** [dragonflydb/dragonfly#1764] opened 2023-08-29 14:57 UTC
**Describe the bug**
We had a few cases in the past when we noticed that maxmemory wasn't enforced and we we able to push new data into DragonflyDB and memory consumption went over maxmemory limit. 

**To Reproduce**
```
docker run -d --name dfly docker.dragonflydb.io/dragonflydb/dragonfly:latest dragonfly --logtostderr --maxmemory 2g
docker exec -it dfly redis-cli
27.0.0.1:6379> debug populate 10000 test 250000
OK
(3.35s)
127.0.0.1:6379> info memory
# Memory
used_memory:2622669152
used_memory_human:2.44GiB
used_memory_peak:2622669152
comitted_memory:2786107392
used_memory_rss:2281201664
used_memory_rss_human:2.12GiB
object_used_memory:2621440000
table_used_memory:1127616
num_buckets:26880
num_entries:10000
inline_keys:10000
strval_bytes:2621440000
updateval_amount:0
listpack_blobs:0
listpack_bytes:0
small_string_bytes:0
pipeline_cache_bytes:0
maxmemory:2147483648
maxmemory_human:2.00GiB
cache_mode:store
maxmemory_policy:noeviction
127.0.0.1:6379> info server
# Server
redis_version:6.2.11
dragonfly_version:df-v1.8.0
redis_mode:standalone
arch_bits:64
multiplexing_api:iouring
tcp_port:6379
uptime_in_seconds:63
uptime_in_days:0
```

**Expected behavior**
Maxmemory is enforced and keys that go above maxmemory are rejected. 

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - Kernel: Linux c56a40ecdb32 5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
 - Containerized?: Docker
 - Dragonfly Version: 1.8.0

**Reproducible Code Snippet**
```
docker run -d --name dfly docker.dragonflydb.io/dragonflydb/dragonfly:latest dragonfly --logtostderr --maxmemory 2g
docker exec -it dfly redis-cli
27.0.0.1:6379> debug populate 10000 test 250000
OK
(3.35s)
127.0.0.1:6379> info memory
```

**Comment by romange** [comment] 2023-08-29 15:23
It's been addressed by https://github.com/dragonflydb/dragonfly/pull/1650 but not yet released

**Comment by eliskovets** [comment] 2023-08-29 18:08
Hi @romange , thank you for looking at it. 
I've just built DFLY from `main` branch and it doesn't seem to be fixed: 
```
127.0.0.1:6379> debug populate 10000 test 250000
OK
(3.16s)
127.0.0.1:6379> info memory
# Memory
used_memory:2622669152
used_memory_human:2.44GiB
used_memory_peak:2622669152
comitted_memory:2785583104
used_memory_rss:2279378944
used_memory_rss_human:2.12GiB
object_used_memory:2621440000
table_used_memory:1127616
num_buckets:26880
num_entries:10000
inline_keys:10000
strval_bytes:2621440000
updateval_amount:0
listpack_blobs:0
listpack_bytes:0
small_string_bytes:0
pipeline_cache_bytes:0
maxmemory:2147483648
maxmemory_human:2.00GiB
cache_mode:store
maxmemory_policy:noeviction
127.0.0.1:6379> info server
# Server
redis_version:6.2.11
dragonfly_version:df-dev
redis_mode:standalone
arch_bits:64
multiplexing_api:iouring
tcp_port:6379
uptime_in_seconds:32
uptime_in_days:0

```
```
git log -1
commit 7c43cbf2b5cd0cd60d6c208a53619256eece6b38 (HEAD -> main, origin/main, origin/HEAD)
Author: Kostas Kyrimis <kostas@dragonflydb.io>
Date:   Tue Aug 29 18:52:46 2023 +0300

    feat: add validation of acl users (#1743)

    * add validation for categories
    * add tests

```

**Comment by romange** [comment] 2023-08-29 19:54
it does not limit the `DEBUG` command, it limits others

**Comment by eliskovets** [comment] 2023-08-29 21:03
Got it. Works as expected with other commands.
```
127.0.0.1:6379> set test 1
(error) ERR Out of memory
```
Should I rename the issue to just DEBUG scope then?

**Comment by romange** [comment] 2023-08-29 21:41
it's working as intended because DEBUG is an internal command and we do not plan to cover it with memory protection

**Closed by romange** 2023-08-29 21:41 UTC
Labels: bug
