### ISSUE TITLE
BZPop bug

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#3276] opened 2024-07-07 06:57 UTC
E20240706 06:12:17.647733  2255 zset_family.cc:1343] BUG: Callback didn't run!  BLOCK//claimed=1 coord_state=6 local_res=0/
E20240706 06:12:11.367316  2255 zset_family.cc:1343] BUG: Callback didn't run!  BLOCK//claimed=1 coord_state=6 local_res=0/

**Comment by romange** [comment] 2024-07-07 07:11
We should not put private links in our public repo (for security considerations).

**Comment by BorysTheDev** [comment] 2024-07-10 14:26
@adiholden @romange I have found only one possible issue. We have 2 steps:
1) Check key presence
2) trans->execute()
During 2nd step we lock db_slice::cb_mu_ and can preempt so if the key is removed we will execute a transaction with a deprecated iterator.
This bug should be fixed by #3229

**Comment by BorysTheDev** [comment] 2024-07-11 12:51
I haven't found using of cluster, replication or snapshotting on this server, so I will try to find another issue

**Comment by BorysTheDev** [comment] 2024-07-19 09:01
I've found one more bug with KEY_MOVE error and have fixed it https://github.com/dragonflydb/dragonfly/pull/3334

But it looks like we have at least one more

**Comment by BorysTheDev** [comment] 2024-07-19 13:45
I haven't found the real reason for this bug, but it looks like the execution order was next:

1) run trans->WaitOnWatch(...)
2) run trans->CancelBlocking(...) 
	2.1) Transaction::coordinator_state_ |= COORD_CANCELLED;
	2.2) Transaction::local_result_ = status; // where status != OK
3) Transaction::local_result_  somehow should be set OK
4) trans->WaitOnWatch(..) returns Transaction::local_result_ // that is already OK

The problem is that I don't see how the 3rd step can happen.
Also, it looks like the 2nd step was done from the connection closing code:
  owner->RegisterBreakHook([res, this](uint32_t) {
    if (res->transaction)
      res->transaction->CancelBlocking(nullptr);
    this->server_family().BreakOnShutdown();
  });

**Comment by BorysTheDev** [comment] 2024-07-22 05:13
coord_state=6 means that operation was canceled

**Comment by dranikpg** [comment] 2024-07-22 07:10
Based on the logs... isn't the key an empty string?

**Comment by BorysTheDev** [comment] 2024-07-22 07:41
> Based on the logs... isn't the key an empty string?

I took it into account that is why I have written about the 3rd step

**Closed** 2024-07-24 12:39 UTC
Labels: bug, Next Up
