### ISSUE TITLE
Strange Slab memory blocking issue

### ISSUE THREAD

**Issue by cbrassel** [dragonflydb/dragonfly#3045] opened 2024-05-14 08:19 UTC
**Describe the bug**
I run dragonflyDB on a production server since a very long time whit out issue, but since Friday where I upgraded to the last 1.18.0 release I had 2 crashs on the server, I run 2 main applications on this server, mysql 8.0 and dragonflyDB.
The symptoms are that mysql use all the cpu and seem's not to be able to process the request's or send data back. Restarting dragonFlyDB or MySQL doesn't resolve the issue, only a reboot of the server solve the problem.

After digging in the graphs I came up with this one : Memory Slab 
![image](https://github.com/dragonflydb/dragonfly/assets/4759371/af49f63d-c4ab-4213-89d5-6dccf76534bb)

Over the last 3 months this graph has been stable, but since Friday it goes up and up .. and only the reboot solve the issue.

Since the new release of dragonflyDB is the only change I have made on Friday .. I suppose it can be a good candidate for this issue.
This morning I have set back to the 1.17.1 release.

**To Reproduce**
Just waiting 2 days ..

**Environment (please complete the following information):**
```
 - OS: ubuntu 22.04.4LTS
 - Kernel: Linux 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
 - Containerized?: Server is on VMware, DragonFlyDB as binary
 - Dragonfly Version: 1.8.0
```
**Reproducible Code Snippet**

**Additional context**
The average memory usage of dragonflyDB is about 28Go, mysql about 24Go of 74Go in total.

**Comment by romange** [comment] 2024-05-15 05:02
@cbrassel please provide "info memory" output from 1.17.1 and then 1.18.0 after 24 hours of running both versions

**Comment by cbrassel** [comment] 2024-05-15 13:14
This is the 1.17.1 memory output :
# Memory
used_memory:4876027424
used_memory_human:4.54GiB
used_memory_peak:4876027424
used_memory_peak_human:4.54GiB
fibers_stack_vms:1604848
fibers_count:49
used_memory_rss:5124042752
used_memory_rss_human:4.77GiB
used_memory_peak_rss:5183430656
maxmemory:54166546022
maxmemory_human:50.45GiB
object_used_memory:4411032760
type_used_memory_STRING:4393906584
type_used_memory_ZSET:17126176
table_used_memory:453446176
num_buckets:807780
num_entries:7958770
inline_keys:597957
listpack_blobs:0
listpack_bytes:0
small_string_bytes:3436687384
pipeline_cache_bytes:8242
dispatch_queue_bytes:0
dispatch_queue_subscriber_bytes:0
dispatch_queue_peak_bytes:26415220
client_read_buffer_peak_bytes:1728512
tls_bytes:5664
cache_mode:store
maxmemory_policy:noeviction

As mentioned it is a production system, so knowing that they can be a production outage I can not just put the new release in production and hoping .. sorry for that

**Comment by romange** [comment] 2024-05-15 13:44
np, we have not seen anything irregular with Dragonfly's memory consumption in 1.18.  we will keep looking.
In any case, this issue unfortunately does not have any actionable inputs, so we do not know what to fix.  
Closing for now. Feel free to reopen if you succeed to get more info.

**Comment by romange** [comment] 2024-05-15 17:55
Actually, we reproduced the problem.

**Comment by romange** [comment] 2024-05-16 05:55
@cbrassel we confirm there is a problem with socket leakage in kernel. The leakage is caused due to the new io_uiring component that was enabled by default in 1.18. Luckily it's easy to fix by passing `--enable_direct_fd=false` flag when running dragonfly. We will also release 1.18.1 with this fix soon.

**Closed** 2024-05-16 06:44 UTC
Labels: bug
