### ISSUE TITLE
unix domain sockets connection possible? 

### ISSUE THREAD

**Issue by osevan** [dragonflydb/dragonfly#93] opened 2022-06-04 08:50 UTC
It is possible to use unix domain sockets and Ipv4 listening on same time? 

Thanks and

Best regards

**Comment by romange** [comment] 2022-06-04 09:05
I did not understand the question. Do you want to use both UDS and TCP port simultaneously?

**Comment by osevan** [comment] 2022-06-04 09:20
> I did not understand the question. Do you want to use both UDS and TCP port simultaneously?

Yes, because in Keydb it is possible via config.

**Comment by romange** [comment] 2022-06-04 09:44
Yes, it's technically possible to implement. Why do you need this feature? In what cases you would want to connect to UDS if you already have TCP

**Comment by osevan** [comment] 2022-06-04 09:55
> Yes, it's technically possible to implement. Why do you need this feature? In what cases you would want to connect to UDS if you already have TCP

For example ,when run keydb and client on single machine and I want avoid IP layer overhead.

On my lab I get 450k get with localhost listening

And 600k get requests when I listen in unix:///tmp/keydb.sock

**Comment by romange** [comment] 2022-06-04 10:00
how about DF? do you get better performance with DF over sockets than keydb with UDS?

**Comment by romange** [comment] 2022-06-06 04:39
@osevan  ? would love to hear your feedback.

**Comment by osevan** [comment] 2022-06-07 15:08
> how about DF? do you get better performance with DF over sockets than keydb with UDS?

At the moment im writing bashscript for automaticaly install webserver with tuning settings - at the moment 1200 lines bashcode only for nginx.


After than ,I want try DF with compiler tuning amd see what i get back and post here

**Comment by romange** [comment] 2022-07-20 05:05
duplicate of #206

**Closed by romange** 2022-07-20 05:05 UTC
Labels: enhancement
