### ISSUE TITLE
oscarsiles/jotlet django app does not work with Dragonfly

### ISSUE THREAD

**Issue by oscarsiles** [dragonflydb/dragonfly#182] opened 2022-06-27 09:12 UTC
I'm trying to test dragonfly on a Django + Channels project, but am getting the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 4073, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 3143, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.NoScriptError: No matching script. Please use EVAL.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/edit.py", line 144, in get
    return self.render_to_response(self.get_context_data())
  File "/workspace/./boards/views.py", line 105, in get_context_data
    self.request.session.create()
  File "/usr/local/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 54, in create
    self.save(must_create=True)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/sessions/backends/cached_db.py", line 54, in save
    super().save(must_create)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 85, in save
    with transaction.atomic(using=using):
  File "/usr/local/lib/python3.10/site-packages/cacheops/transaction.py", line 77, in __exit__
    self._no_monkey.__exit__(self, exc_type, exc_value, traceback)
  File "/usr/local/lib/python3.10/site-packages/cachalot/monkey_patch.py", line 179, in inner
    original(self, exc_type, exc_value, traceback)
  File "/usr/local/lib/python3.10/site-packages/django/db/transaction.py", line 299, in __exit__
    connection.set_autocommit(True)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 450, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 692, in run_and_clear_commit_hooks
    func()
  File "/usr/local/lib/python3.10/site-packages/cacheops/transaction.py", line 30, in commit
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/cacheops/invalidation.py", line 32, in invalidate_dict
    load_script('invalidate')(keys=[prefix], args=[
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 4079, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 3143, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Error running script (call to 7473b25dd38dbe903434e05cfa843a3f40233dfb): @enable_strict_lua:17: user_script:4: Script attempted to access nonexistent global variable 'cjson'
```

**To Reproduce**
1. Create Django project with redis cache
2. Load a page that uses cache

**Comment by romange** [comment] 2022-06-27 09:15
@oscarsiles  Can you please tell what dragonfly version you are running? We had this bug in previous versions but it has been fixed in the latest one.

**Comment by oscarsiles** [comment] 2022-06-27 09:24
@romange , you're right, my docker image hadn't updated so force updating fixed that particular issue. However, now when I try to load the page dragonfly reaches 100% CPU and is stuck (blocking the rest of the page from loading).

**Comment by romange** [comment] 2022-06-27 09:25
how do you run dragonfly?

**Comment by oscarsiles** [comment] 2022-06-27 09:26
Running via docker on WSL2, using the following docker-compose settings:

```
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    restart: unless-stopped
    command: --cache_mode=true
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
```

**Comment by romange** [comment] 2022-06-27 10:54
@oscarsiles  your help will be greatly appreciated. If you can not post the log, then maybe the Django code that can reliably reproduce the problem?

**Comment by oscarsiles** [comment] 2022-06-27 10:55
@romange apologies, in the middle of meetings! Will post logs once I'm able to later today.

**Comment by romange** [comment] 2022-06-27 14:59
Can I assume that running https://github.com/oscarsiles/jotlet  integrated with dragonfly triggers this bug @oscarsiles  ?

**Comment by oscarsiles** [comment] 2022-06-27 16:56
Yes, that's right.

**Comment by romange** [comment] 2022-06-28 07:47
@oscarsiles  how do I start you django app? I've installed your `requirements-dev.txt` but not sure how to run it from the repo 🤔

**Comment by romange** [comment] 2022-09-09 07:46
@alexted - look at #184 - we confirmed that this library does not work with DF yet.
1. It requires cjson lua support
2. It uses relaxed Lua scripts that access run-time generated, undeclated keys (DF does not support it today).

**Comment by romange** [comment] 2023-04-29 13:17
Should work if dragonfly is running with flags: `--default_lua_config="allow-undeclared-keys disable-atomicity"` or `--default_lua_config="allow-undeclared-keys"`. The latter runs Dragonfly with eval call under a global lock (not recommended due to its low performance ). The former runs lua scripts non-atomically. Lua atomicity seems to be not needed for this use-case anyway.

**Closed by romange** 2023-04-29 13:17 UTC
Labels: bug
