### ISSUE TITLE
 Failed in deducing any cgroup limits when the instance starts

### ISSUE THREAD

**Issue by boomballa** [dragonflydb/dragonfly#3812] opened 2024-09-27 12:06 UTC
**Describe the bug**
When the instance starts, a deduce cgroup limit error is reported.

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/ce560071-29ad-4ee1-8737-298d213ccfd5)

**Environment (please complete the following information):**
 - OS: [Debian GNU/Linux 11]
 - Kernel: Linux  5.10.0-30-amd64 #1 SMP Debian 5.10.218-1 (2024-06-01) x86_64 GNU/Linux
 - Containerized?: [Bare Metal, Docker, Docker Compose, Docker Swarm, Kubernetes, Other]
 - Dragonfly Version: [v1.23.0]

**Additional context**
When the instance starts, a deduce cgroup limit error is reported.  The directory that reports the error is consistent and the directory exists. At first I thought I didn't have enough permissions, but then I tried to start it with sudo permissions, and the result was still the same. The error doesn't affect the startup of the instance, and the subsequent use of the instance is normal, but I'm not sure if it does or not, or if it only affects it in certain scenarios. If it doesn't, may I suggest changing this to warning or something else? Of course, if there is a problem with the deduce logic, it would be perfect to fix the error output. 😄

**Comment by kostasrim** [comment] 2024-09-27 12:12
Hi @boomballa and thank you for reporting. Are you running this on docker or ?

**Comment by boomballa** [comment] 2024-09-28 09:02
> Hi @boomballa and thank you for reporting. Are you running this on docker or ?

@kostasrim  Hello, I am running directly on top of a physical machine and not using docker or k8s.

**Comment by kostasrim** [comment] 2024-10-02 13:31
Hi @boomballa, apologies for late reply.

The problem is that dragonfly is trying to read the `cgroup memory` and `cpu controllers` and they are missing. (cgroups are used to limit available resources of a system among its users)

In your `cat command` output there is no `memory.max, cpu.max etc`. You only have `memory.pressure && cpu.pressure`.

So first let's do a small inspection of your configuration. Plz paste the results of the following commands

1. `mount -l | grep cgroup`
^^ this should be cgroup2 based on the paths you provided but let's check
2. `cat /sys/fs/cgroup/cgroup.controllers`
^^ this will tell us which controllers the kernel is enabled
3. did you roll out or made any changes to the kernel config or you just using debian 11 as is (meaning that you just installed it without changing any of the prepackaged configuration of the kernel) 
4. paste the complete output of `ls` within the `/sys/fs/cgroup/user.slice/rest_of_path_here`

All in all, we log this as `ERROR` because it's important for the user to know that we are not restricting the resources

**Comment by boomballa** [comment] 2024-10-03 02:39
> 你好@boomballa，抱歉回复迟了。
> 
> 问题是，dragonfly 正在尝试读取`cgroup memory`和`cpu controllers`，但它们丢失了。（cgroups 用于限制系统在其用户之间的可用资源）
> 
> 您的输出中`cat command`没有`memory.max, cpu.max etc`。您只有`memory.pressure && cpu.pressure`。
> 
> 首先让我们对您的配置进行一下小检查。请粘贴以下命令的结果
> 
> 1. `mount -l | grep cgroup`
>    ^^根据你提供的路径，这应该是 cgroup2，但让我们检查一下
> 2. `cat /sys/fs/cgroup/cgroup.controllers`
>    ^^这将告诉我们内核启用了哪些控制器
> 3. 您是否推出或对内核配置进行了任何更改，或者您只是按原样使用 debian 11（这意味着您只是安装了它而没有更改内核的任何预打包配置）
> 4. `ls`粘贴完整输出`/sys/fs/cgroup/user.slice/rest_of_path_here`
> 
> 总而言之，我们记录这一点是`ERROR`因为让用户知道我们不会根据他们的组来限制资源是很重要的（也就是说，如果有些系统不包含任何这些资源，我们应该相应地处理它们）。

1. shell:~$ mount -l |grep cgroup
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)

2. shell:~$ cat /sys/fs/cgroup/cgroup.controllers
cpuset cpu io memory hugetlb pids rdma

3. Although I am not a system administrator, I have inquired and we have not made any other changes to the debian11 system kernel.

4. shell:~$ ls /sys/fs/cgroup/user.slice/
cgroup.controllers      cgroup.subtree_control  cpuset.cpus.partition   io.pressure             memory.low              memory.swap.current     user-0.slice/
cgroup.events           cgroup.threads          cpuset.mems             io.stat                 memory.max              memory.swap.events      user-1521.slice/
cgroup.freeze           cgroup.type             cpuset.mems.effective   io.weight               memory.min              memory.swap.high        user-9488.slice/
cgroup.max.depth        cpu.max                 cpu.stat                memory.current          memory.numa_stat        memory.swap.max
cgroup.max.descendants  cpu.pressure            cpu.weight              memory.events           memory.oom.group        pids.current
cgroup.procs            cpuset.cpus             cpu.weight.nice         memory.events.local     memory.pressure         pids.events
cgroup.stat             cpuset.cpus.effective   io.max                  memory.high             memory.stat             pids.max

The configuration you need I pasted into the above location, thanks for troubleshooting and following up on this issue.

**Comment by kostasrim** [comment] 2024-10-03 08:40
Hi @boomballa, I think I might have identified the problem but could you also provide the output of the following commands:

1. `ls /sys/fs/cgroup/`  (watch not `user.slice` subdirectory)
2. `ls` on the paths that dragonfly output as errors -> `failed to deduce cgroup` (there are two paths mentioned there, plz `ls` them and send me the output). You also included this output on the first picture, but it's not clear to me if it's truncated or not.

All in all, what I think is:

1. We only parse `cgroups` for version `1`. We should also include parsing global cgroup config for version 2. The main difference is that the former includes one subdirectory for each controller (for example, `/sys/fs/cgroup/memory/memory.max`) while the newer version groups all the controllers under the same folder (for example `/sys/fs/cgroup/memory.max`) and we only read the folders as of `version 1`.

2. We also read the folders of the `user's cgroup` (the ones with `path` seen in the output of `dragonfly`). I would be interested to know why these folders do not contain any of the files we try to read. 

I am pretty sure if I fix (1) the error will go away. But I still do want to understand why the (2) are not parsed

**Comment by kostasrim** [comment] 2024-10-03 11:21
hmm I also discovered:

```
cpu.max
A read-write two value file which exists on non-root cgroups. The default is “max 100000”.
```

So I expect that for (1) above there won't be any `cpu.max`

(2) I am interested to see what the output of that is: "`ls` on the paths that dragonfly output as error"

**Comment by kostasrim** [comment] 2024-10-03 11:23
Same for `memory.max`: 

```
memory.max
A read-write single value file which exists on non-root cgroups. The default is “max”.
```

So for system config we should actually be looking at `/sys/fs/cgroup/system.slice`. (TODO to verify this)

**Comment by boomballa** [comment] 2024-10-04 07:43
@kostasrim  Thank you for your patience in following up on this issue

1. ls /sys/fs/cgroup/

shell:~$ ls /sys/fs/cgroup/
```
cgroup.controllers      cgroup.procs            cgroup.threads         cpuset.mems.effective  dev-mqueue.mount  io.cost.qos  memory.numa_stat  -.mount                        sys-kernel-debug.mount    user.slice
cgroup.max.depth        cgroup.stat             cpu.pressure           cpu.stat               init.scope        io.pressure  memory.pressure   sys-fs-fuse-connections.mount  sys-kernel-tracing.mount
cgroup.max.descendants  cgroup.subtree_control  cpuset.cpus.effective  dev-hugepages.mount    io.cost.model     io.stat      memory.stat       sys-kernel-config.mount        system.slice
```
2. The error message is as below:
`E20241004 15:15:21.999136 184759 dfly_main.cc:541] Failed in deducing any cgroup limits with paths /sys/fs/cgroup//user.slice/user-1521.slice/session-37522.scope and /sys/fs/cgroup//user.slice/user-1521.slice/session-37522.scope`

shell:~$ ls /sys/fs/cgroup//user.slice/user-1521.slice/session-37522.scope
```
cgroup.controllers  cgroup.freeze     cgroup.max.descendants  cgroup.stat             cgroup.threads  cpu.pressure  io.pressure      pids.current  pids.max
cgroup.events       cgroup.max.depth  cgroup.procs            cgroup.subtree_control  cgroup.type     cpu.stat      memory.pressure  pids.events
```
shell:~$ ls /sys/fs/cgroup//user.slice/user-1521.slice/session-37522.scope
```
cgroup.controllers  cgroup.freeze     cgroup.max.descendants  cgroup.stat             cgroup.threads  cpu.pressure  io.pressure      pids.current  pids.max
cgroup.events       cgroup.max.depth  cgroup.procs            cgroup.subtree_control  cgroup.type     cpu.stat      memory.pressure  pids.events
```
The error should show the same directory.



There are indeed cpu.max and memory.max directories in the /sys/fs/cgroup/system.slice directory
```
shell$ cat  /sys/fs/cgroup/system.slice/cpu.max
max 100000
shell$ cat  /sys/fs/cgroup/system.slice/memory.max
max
```

**Comment by boomballa** [comment] 2024-10-04 07:50
@kostasrim I think the cpu.max and memory.max configurations should be read in the /sys/fs/cgroup/user.slice/ directory? Because its configuration should normally not be quite the same as system's. So reading in the /sys/fs/cgroup/system.slice/ directory may not be quite right either.
These two files don't exist in the user-slice/session-UID directory and should be inherited from the configuration of the above files.

shell:~$ cat /sys/fs/cgroup//user.slice/cpu.max
`max 100000`
shell:~$ cat /sys/fs/cgroup//user.slice/memory.max
`max`

**Comment by kostasrim** [comment] 2024-10-04 08:49
Hi @boomballa,

> ls /sys/fs/cgroup/

As expected here there are no `cpu.max` files here. So this folder is not of interest.

I am not familiar with `cgroups` so I had to spend a little time on them yesterday (and I am not sure I grasp them fully to be honest as the docs are not very clear for certain concepts). From my understanding, they are hierarchical and each sub-directory in the tree must contain all those controller files (at least on my system this is the case).

I also think you are right about not polling `/sys/fs/cgroup/system.slice/`. All `processes` not related with the system are under the `/sys/fs/cgroup/user.slice`. If a process is spawned by `systemd` from an unit config file it's called a `service` whereas processes that are registered are runtime with systemd are called `scopes` and these two create those long paths/hierarchies we see.

So if I understand this correctly, df should poll `sys/fs/cgroup/user/slice` first and then check if there are more specific restrictions in their respective scope, i,e.  poll `/sys/fs/cgroup//user.slice/user-1521.slice/session-37522.scope`. I will need to verify this but this seems to be the right behaviour.

All in all, there is something I want to understand before I move on with any of the aforementioned changes. Specifically, I am interested in `/sys/fs/cgroup//user.slice/user-1521.slice/session-37522.scope` and why it does not inherit/contain any of the `cpu.max` files ? From my understanding, this should not be the case, since any of those folders that contain any process should also inherit and contain those controller files which clearly, from your `output` this is `not` the case. 

Can you also traverse the directories above `session-37522.scope` and let me know if there are any `cpu.max` files there? In the meantime I will try to make sense of this

**Comment by kostasrim** [comment] 2024-10-07 08:28
Hi @boomballa thank you for getting back to me:

> First of all, the restrictions of each tier should depend on the cgroup.subtree_control file of the upper tier, 

I think restrictions are inherited from `parent` to the `subdirectory/child`. This is the case at least on my system and the rest of the cases I am aware. IMO my main question is why they are not there for `your case`. Could be because of some configuration, but based on my limited understanding this should be the case

As for cgroups, they are hierarchical as you say.

> So I understand that if we have to limit cpu and memory or even io metrics at startup, the user who starts Dragonfly must have sudo privileges to modify the relevant controller file in order to limit the use of server resources by processes or sessions ?

No, all of these are configurable via `command line flags, e.g. --maxmemory, --proactor_threads etc` so you don't really need to manually fix those files. And to be honest, I don't think you should manually tweak those files unless you are specifically running this in some docker container. Otherwise, all of the values of the cgroup hierarchy should be inherited. As I said, the main question is why in your system these are not being propagated from the parent to the child in the hierarchy tree. This should be addressed by whoever owns the system and is not something I can offer much insight.

> Dragonfly requires a very high version of the system kernel, the use of cgroupV2 may be more and more in the future, this problem may indeed need to have a reasonable way to adjust a bit,

Well we do have logic to parse cgroupv1 as well. If you want to restrict dragonfly resources either:

1. Use explicit flags like `maxmemory` etc
2. Make sure that your cgroup hierarchy is available, that is the cgroup scope should contain the controllers for dragonfly to poll

All in all, our bandwidth is kinda limited to fully pursue this for all systems so what I can slightly help with is the (2) by also adding logic to parse the controllers found in `/sys/fs/cgroup/user.slice` such that if, like in your case, the controllers are missing from subdirectories, df will at least try to parse them from the first parent in the hierarchy `/sys/fs/cgroup/user.slice`. This would at least get `rid of the warning` such that it doesn't cause any confusion.

All in all:

1. I will address my PR to poll `/sys/fs/cgroup/user.slice` which should help you with the warning.
2. I would suggest you to either use explicit configuration such `maxmemory etc` or to see why in your system the cgroup subdirs do not contain the controllers

**Comment by boomballa** [comment] 2024-10-08 02:34
Hi @kostasrim  Thanks for the reply.  

> No, all of these are configurable via command line flags, e.g. --maxmemory, --proactor_threads etc so you don't really need to manually fix those files. And to be honest, I don't think you should manually tweak those files unless you are specifically running this in some docker container. Otherwise, all of the values of the cgroup hierarchy should be inherited. As I said, the main question is why in your system these are not being propagated from the parent to the child in the hierarchy tree. This should be addressed by whoever owns the system and is not something I can offer much insight.

You're right, these things really shouldn't be specified manually by the user, I manually tweaked it knowledge for the sake of experimentation and to give us a reference, and I'll still try to limit the use of the resource with a parameter instead of tweaking it manually in the future.

> Log line format: [IWEF]yyyymmdd hh:mm:ss.uuuuuu threadid file:line] msg
E20240923 18:21:44.722133 23445 dfly_main.cc:541] Failed in deducing any cgroup limits with paths /sys/fs/cgroup//user.slice/user-1521.slice/session-20732.scope and /sys/fs/cgroup//user.slice/user-1521.slice/session-20732.scope

It's just that the error, if it doesn't affect the use of the main process, is a reminder of whether there's a problem with the official handling of some part of the df startup process and whether it needs to be handled to make the startup process a bit more harmonized. 😃

**Closed** 2024-10-10 16:15 UTC
Labels: bug
