### ISSUE TITLE
Dragonfly as memcached crashes and can't load dump

### ISSUE THREAD

**Issue by sbkoto** [dragonflydb/dragonfly#1730] opened 2023-08-24 09:26 UTC
**Describe the bug**
Dragonfly periodically crashes and after loading does not load the dump. It used as memcached with port 11211. 

**To Reproduce**
`ExecStart=/usr/bin/dragonfly --log_dir=/var/log/dragonfly --dir=/var/lib/dragonfly --dbfilename=dragonfly_dump --maxmemory=35gb --memcached_port=11211 --snapshot_cron="*/5 * * * *" --logtostderr`

**Screenshots**
![image](https://github.com/dragonflydb/dragonfly/assets/138572227/f8939a09-413b-470c-9508-8675b87b4033)

**Environment (please complete the following information):**
```
 - OS: [ubuntu 20.04]
 - Kernel: Linux 5.15.0-79-generic #86~20.04.2-Ubuntu SMP Mon Jul 17 23:27:17 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - Containerized?: bare metal
 - Dragonfly Version: 1.8.0 from binary
```

**Additional context**
Crash with:
`dragonfly[8873]: F20230824 03:35:00.286943  8879 db_slice.cc:497] Check failed: 1u == db->mcflag.Erase(it->first) (1 vs. 0)
`
[log_crash.txt](https://github.com/dragonflydb/dragonfly/files/12427800/log_crash.txt)

Cant start with:
`Aug 24 03:35:00  dragonfly[15899]: F20230824 03:35:00.996003 15900 facade.cc:134] Check failed: Protocol::REDIS == protocol()`
[log_start.txt](https://github.com/dragonflydb/dragonfly/files/12427801/log_start.txt)

**Comment by romange** [comment] 2023-08-24 10:05
Thanks @sbkoto  for reporting this. How do you write your data? Is it possible to reproduce on my side?

**Comment by romange** [comment] 2023-08-24 10:12
@kostasrim  I will need your help with this. There are two bugs here. The first crash I will take on myself. Could you please check out the second crash (when loading the snapshot with Dragonfly running with Memcache prorotocl) ?

**Comment by sbkoto** [comment] 2023-08-24 10:12
@romange write from php backend, it is hardly possible to try, but I can give approximate statistics on loading and the number of clients is 15000-19000
![image](https://github.com/dragonflydb/dragonfly/assets/138572227/2cbe5994-cf25-4fad-ae7e-d703c26fcb93)

**Comment by romange** [comment] 2023-08-24 10:15
ah nice, you are ranning master/slave replication with memcache? 
1. Why do you guys need replication? for H/A ?
2. I am more interested in sample of SET commands. Do you guys use memcache flags?

**Comment by kostasrim** [comment] 2023-08-24 10:22
@romange Just my name, let me go over the whole issue, will ping soon

**Comment by sbkoto** [comment] 2023-08-24 11:40
> ah nice, you are running master/slave replication with memcache?
> 
> 1. Why do you guys need replication? for H/A ?
> 2. I am more interested in a sample of SET commands. Do you guys use memcache flags?
1. for ha, but in this case replica clear storage like master :C 
2. used libmemcached (php), in particular awesome-memcached, fastlz flags

**Comment by romange** [comment] 2023-08-24 12:10
@sbkoto Unfortunately I can not find the root cause for the first crash but I will provide the intermediate fix. does it happen once a day? once a week?

**Comment by sbkoto** [comment] 2023-08-24 12:32
> @sbkoto Unfortunately I can not find the root cause for the first crash but I will provide the intermediate fix. does it happen once a day? once a week?
two days testing on prod
![image](https://github.com/dragonflydb/dragonfly/assets/138572227/9db9ba29-d2b3-4b61-8b9f-ecb3987bf859)

**Comment by kostasrim** [comment] 2023-08-24 14:11
@sbkoto I managed to reproduce the second issue. I will address it soon

**Comment by sbkoto** [comment] 2023-08-24 18:02
compiled from main and run after another crash, popcorn ready too :)

**Comment by kostasrim** [comment] 2023-08-24 18:08
I love :popcorn: (I want a [party-parot](https://cultofthepartyparrot.com/) emoji on GH like on slack). Long story short, the issue is on how we report errors + handle certain functions in replication when memcache protocol is used (and generally our error reporting is kinda broken on memcache protocol). Good news is that I will have that fixed by tomorrow. I expect that this might uncover some other underline bug but these should be easy to fix/reproduce once I got the main fix in. Bare with me, and we will handle everything :rocket:

**Comment by romange** [comment] 2023-08-24 19:18
@sbkoto you built it from source after my fix?  😮

**Comment by sbkoto** [comment] 2023-08-24 19:47
> @sbkoto you built it from source after my fix? 😮

yep

**Comment by romange** [comment] 2023-08-24 20:13
Cool. Please check the log whether we have any errors there.

**Comment by romange** [comment] 2023-08-25 10:29
@sbkoto any updates?

**Comment by sbkoto** [comment] 2023-08-25 10:50
> @sbkoto any updates?

17 hours uptime and crash again:
[25_08_crash.txt](https://github.com/dragonflydb/dragonfly/files/12438307/25_08_crash.txt)
start: 
[25_08_start.txt](https://github.com/dragonflydb/dragonfly/files/12438375/25_08_start.txt)

But the biggest pain is that he did not upload the keys with the correct snapshot, which was taken 10 minutes before the fall:
```
Aug 25 13:23:56 dragonfly[55485]: I20230825 13:23:56.863006 55485 server_family.cc:1031] Loading /var/lib/dragonfly/dragonfly_dump-summary.dfs
Aug 25 13:23:56  dragonfly[55485]: I20230825 13:23:56.864239 55488 server_family.cc:1076] Load finished, num keys read: 0
```
![image](https://github.com/dragonflydb/dragonfly/assets/138572227/857e8e0a-99b0-4126-8892-604d76eaeeb6)

Replica, when an empty master appeared, also erased its keys, although here the optimal strategy is to switch roles and pull the keys from the replica to the master back.

**Comment by sbkoto** [comment] 2023-08-25 11:00
dump looks like this:
![image](https://github.com/dragonflydb/dragonfly/assets/138572227/8515c442-b90f-4ca1-a3a1-5348b2fb373d)

**Comment by romange** [comment] 2023-08-25 13:58
@sbkoto the good news is that it seems we fixed one of the issues.
And I think I know where the problem is with this crash. I will hack something soon and push into a special branch.
Seems you can manage yourself with compiling our code so I hope it will allow us to test quickly if my guess is good.

**Comment by romange** [comment] 2023-08-25 13:59
@sbkoto can you please DM me on discord?

**Comment by sbkoto** [comment] 2023-09-04 10:04
after weekend crashed:

```
Sep 04 12:20:22 dragonfly dragonfly[289403]: I20230904 12:20:22.875350 289406 server_family.cc:648] Saving "/var/lib/dragonfly/dragonfly_dump-summary.dfs" finished after 22.9 s
Sep 04 12:22:09 dragonfly dragonfly[289403]: F20230904 12:22:09.265354 289412 facade.cc:139] Check failed: Protocol::REDIS == protocol()
Sep 04 12:22:09 dragonfly dragonfly[289403]: *** Check failure stack trace: ***
Sep 04 12:22:09 dragonfly dragonfly[289403]:     @     0x55a9ea291150  google::LogMessage::Fail()
Sep 04 12:22:09 dragonfly dragonfly[289403]:     @     0x55a9ea298343  google::LogMessage::SendToLog()
Sep 04 12:22:09 dragonfly dragonfly[289403]:     @     0x55a9ea290b07  google::LogMessage::Flush()
Sep 04 12:22:09 dragonfly dragonfly[289403]:     @     0x55a9ea29248f  google::LogMessageFatal::~LogMessageFatal()
Sep 04 12:22:09 dragonfly dragonfly[289403]:     @     0x55a9ea192edc  facade::ConnectionContext::operator->()
Sep 04 12:22:09 dragonfly dragonfly[289403]:     @     0x55a9e9ee52b2  dfly::Service::DispatchCommand()
Sep 04 12:22:09 dragonfly dragonfly[289403]:     @     0x55a9e9eea5e2  dfly::Service::DispatchMC()
Sep 04 12:22:09 dragonfly dragonfly[289403]:     @     0x55a9ea18f8e2  facade::Connection::ParseMemcache()
Sep 04 12:22:09 dragonfly dragonfly[289403]:     @     0x55a9ea18fbf8  facade::Connection::IoLoop()
Sep 04 12:22:09 dragonfly dragonfly[289403]:     @     0x55a9ea18ff17  facade::Connection::ConnectionFlow()
Sep 04 12:22:09 dragonfly dragonfly[289403]:     @     0x55a9ea190d53  facade::Connection::HandleRequests()
Sep 04 12:22:09 dragonfly dragonfly[289403]:     @     0x55a9ea23ca54  util::ListenerInterface::RunSingleConnection()
Sep 04 12:22:09 dragonfly dragonfly[289403]:     @     0x55a9ea23cd97  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberENS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail15WorkerFiberImplIZNS8_17ListenerInterface13RunAcceptLoopEvEUlvE0_JEEC4IS7_EESt17basic_string_viewIcSt11char_traitsIcEERKNS0_12preallocatedEOT_OSD_EUlOS4_E_EEEEvNS1_10transfer_tE
Sep 04 12:22:09 dragonfly dragonfly[289403]:     @     0x7fde5bca91cf  make_fcontext
Sep 04 12:22:09 dragonfly dragonfly[289403]: *** SIGABRT received at time=1693819329 on cpu 8 ***
Sep 04 12:22:09 dragonfly dragonfly[289403]: PC: @     0x7fde5b37500b  (unknown)  raise
Sep 04 12:22:10 dragonfly systemd[1]: dragonfly.service: Main process exited, code=killed, status=6/ABRT

```

systemd restart service:

```
Sep 04 12:22:10 dragonfly dragonfly[328875]: I20230904 12:22:10.516611 328875 proactor_pool.cc:147] Running 10 io threads
Sep 04 12:22:10 dragonfly dragonfly[328875]: I20230904 12:22:10.542805 328875 server_family.cc:240] Data directory is "/var/lib/dragonfly"
Sep 04 12:22:10 dragonfly dragonfly[328875]: I20230904 12:22:10.543401 328875 server_family.cc:1058] Loading /var/lib/dragonfly/dragonfly_dump-summary.dfs
Sep 04 12:22:10 dragonfly dragonfly[328875]: I20230904 12:22:10.547504 328880 listener_interface.cc:97] sock[33] AcceptServer - listening on port 6379
Sep 04 12:22:10 dragonfly dragonfly[328875]: I20230904 12:22:10.547540 328881 listener_interface.cc:97] sock[34] AcceptServer - listening on port 11211
Sep 04 12:22:10 dragonfly dragonfly[328875]: F20230904 12:22:10.549086 328876 facade.cc:139] Check failed: Protocol::REDIS == protocol()
Sep 04 12:22:10 dragonfly dragonfly[328875]: *** Check failure stack trace: ***
Sep 04 12:22:10 dragonfly dragonfly[328875]: F20230904 12:22:10.549796 328877 facade.cc:139] Check failed: Protocol::REDIS == protocol()
Sep 04 12:22:10 dragonfly dragonfly[328875]: *** Check failure stack trace: ***
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d8f150  google::LogMessage::Fail()
Sep 04 12:22:10 dragonfly dragonfly[328875]: F20230904 12:22:10.549796 328877 facade.cc:139] Check failed: Protocol::REDIS == protocol() F20230904 12:22:10.550238 328881 facade.cc:139] Check failed: Protocol::REDIS == protocol()
Sep 04 12:22:10 dragonfly dragonfly[328875]: *** Check failure stack trace: ***
Sep 04 12:22:10 dragonfly dragonfly[328875]: F20230904 12:22:10.549796 328877 facade.cc:139] Check failed: Protocol::REDIS == protocol() F20230904 12:22:10.550238 328881 facade.cc:139] Check failed: Protocol::REDIS == protocol() F20230904 12:22:10.550312 328880 facade.cc:139] Check failed: Protocol::REDIS == protocol()
Sep 04 12:22:10 dragonfly dragonfly[328875]: *** Check failure stack trace: ***
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d8f150  google::LogMessage::Fail()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d96343  google::LogMessage::SendToLog()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d8f150  google::LogMessage::Fail()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d8f150  google::LogMessage::Fail()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d8eb07  google::LogMessage::Flush()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d96343  google::LogMessage::SendToLog()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d96343  google::LogMessage::SendToLog()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d96343  google::LogMessage::SendToLog()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d9048f  google::LogMessageFatal::~LogMessageFatal()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d8eb07  google::LogMessage::Flush()
Sep 04 12:22:10 dragonfly dragonfly[328875]: F20230904 12:22:10.549796 328877 facade.cc:139] Check failed: Protocol::REDIS == protocol() F20230904 12:22:10.550238 328881 facade.cc:139] Check failed: Protocol::REDIS == protocol() F20230904 12:22:10.550312 328880 facade.cc:139] Check failed: Protocol::REDIS == protocol() F20230904 12:22:10.551431 328879 facade.cc:139] Check failed: Protocol::REDIS == protocol()
Sep 04 12:22:10 dragonfly dragonfly[328875]: *** Check failure stack trace: ***
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d8eb07  google::LogMessage::Flush()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d8eb07  google::LogMessage::Flush()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d9048f  google::LogMessageFatal::~LogMessageFatal()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d8f150  google::LogMessage::Fail()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d9048f  google::LogMessageFatal::~LogMessageFatal()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c90edc  facade::ConnectionContext::operator->()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d9048f  google::LogMessageFatal::~LogMessageFatal()
Sep 04 12:22:10 dragonfly dragonfly[328875]: F20230904 12:22:10.549796 328877 facade.cc:139] Check failed: Protocol::REDIS == protocol() F20230904 12:22:10.550238 328881 facade.cc:139] Check failed: Protocol::REDIS == protocol() F20230904 12:22:10.550312 328880 facade.cc:139] Check failed: Protocol::REDIS == protocol() F20230904 12:22:10.551431 328879 facade.cc:139] Check failed: Protocol::REDIS == protocol() F20230904 12:22:10.552148 328878 facade.cc:139] Check failed: Protocol::REDIS == protocol()
Sep 04 12:22:10 dragonfly dragonfly[328875]: *** Check failure stack trace: ***
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d96343  google::LogMessage::SendToLog()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d8eb07  google::LogMessage::Flush()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad49e32b2  dfly::Service::DispatchCommand()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c90edc  facade::ConnectionContext::operator->()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c90edc  facade::ConnectionContext::operator->()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c90edc  facade::ConnectionContext::operator->()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d8f150  google::LogMessage::Fail()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d9048f  google::LogMessageFatal::~LogMessageFatal()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad49e85e2  dfly::Service::DispatchMC()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad49e32b2  dfly::Service::DispatchCommand()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad49e32b2  dfly::Service::DispatchCommand()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad49e32b2  dfly::Service::DispatchCommand()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d96343  google::LogMessage::SendToLog()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c90edc  facade::ConnectionContext::operator->()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c8d8e2  facade::Connection::ParseMemcache()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad49e85e2  dfly::Service::DispatchMC()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad49e85e2  dfly::Service::DispatchMC()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad49e85e2  dfly::Service::DispatchMC()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d8eb07  google::LogMessage::Flush()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad49e32b2  dfly::Service::DispatchCommand()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c8e528  facade::Connection::ConnectionFlow()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c8d8e2  facade::Connection::ParseMemcache()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c8d8e2  facade::Connection::ParseMemcache()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c8d8e2  facade::Connection::ParseMemcache()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d9048f  google::LogMessageFatal::~LogMessageFatal()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad49e85e2  dfly::Service::DispatchMC()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c8ed53  facade::Connection::HandleRequests()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c8e528  facade::Connection::ConnectionFlow()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c8e528  facade::Connection::ConnectionFlow()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c8e528  facade::Connection::ConnectionFlow()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c8d8e2  facade::Connection::ParseMemcache()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c8ed53  facade::Connection::HandleRequests()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d3aa54  util::ListenerInterface::RunSingleConnection()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c8ed53  facade::Connection::HandleRequests()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c8ed53  facade::Connection::HandleRequests()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c8e528  facade::Connection::ConnectionFlow()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d3ad97  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberENS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail15WorkerFiberImplIZNS8_17ListenerInterface13RunAcceptLoopEvEUlvE0_JEEC4IS7_EESt17basic_string_viewIcSt11char_traitsIcEERKNS0_12preallocatedEOT_OSD_EUlOS4_E_EEEEvNS1_10transfer_tE
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c90edc  facade::ConnectionContext::operator->()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d3aa54  util::ListenerInterface::RunSingleConnection()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d3aa54  util::ListenerInterface::RunSingleConnection()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d3aa54  util::ListenerInterface::RunSingleConnection()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4c8ed53  facade::Connection::HandleRequests()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d3ad97  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberENS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail15WorkerFiberImplIZNS8_17ListenerInterface13RunAcceptLoopEvEUlvE0_JEEC4IS7_EESt17basic_string_viewIcSt11char_traitsIcEERKNS0_12preallocatedEOT_OSD_EUlOS4_E_EEEEvNS1_10transfer_tE
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d3ad97  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberENS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail15WorkerFiberImplIZNS8_17ListenerInterface13RunAcceptLoopEvEUlvE0_JEEC4IS7_EESt17basic_string_viewIcSt11char_traitsIcEERKNS0_12preallocatedEOT_OSD_EUlOS4_E_EEEEvNS1_10transfer_tE
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x7fcaf94c51cf  make_fcontext
Sep 04 12:22:10 dragonfly dragonfly[328875]: *** SIGABRT received at time=1693819330 on cpu 0 ***
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x564ad4d3ad97  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberENS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail15WorkerFiberImplIZNS8_17ListenerInterface13RunAcceptLoopEvEUlvE0_JEEC4IS7_EESt17basic_string_viewIcSt11char_traitsIcEERKNS0_12preallocatedEOT_OSD_EUlOS4_E_EEEEvNS1_10transfer_tE
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x7fcaf94c51cf  make_fcontext
Sep 04 12:22:10 dragonfly dragonfly[328875]: PC: @     0x7fcaf8b9100b  (unknown)  raise
Sep 04 12:22:10 dragonfly dragonfly[328875]: [failure_signal_handler.cc : 332] RAW: Signal 6 raised at PC=0x7fcaf8b9100b while already in AbslFailureSignalHandler()
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x7fcaf94c51cf  make_fcontext
Sep 04 12:22:10 dragonfly dragonfly[328875]:     @     0x7fcaf94c51cf  make_fcontext
Sep 04 12:22:10 dragonfly systemd[1]: dragonfly.service: Main process exited, code=killed, status=6/ABRT

```

**Comment by romange** [comment] 2023-10-26 18:38
@sbkoto we are closing the issue, feel free to reopen if crashes still happen.

**Closed by romange** 2023-10-26 18:38 UTC
Labels: bug, important
