### ISSUE TITLE
dragonfly.WARNING Socket error system:110 Connection timed out

### ISSUE THREAD

**Issue by kissingtiger** [dragonflydb/dragonfly#1431] opened 2023-06-19 03:10 UTC
**Environment (please complete the following information):**
 - OS: Alibaba Cloud Linux release 3 (Soaring Falcon) 
 - Kernel: 5.10.134-13.1.al8.x86_64
 - Dragonfly Version: dragonfly dev-0000000

dragonfly.WARNING :
W20230616 16:25:13.794246  2496 dragonfly_connection.cc:522] Socket error system:110 Connection timed out
W20230616 16:25:13.794252  2613 dragonfly_connection.cc:522] Socket error system:110 Connection timed out
W20230616 16:25:13.794232  2326 dragonfly_connection.cc:522] Socket error system:110 Connection timed out
W20230616 16:25:13.794250  2548 dragonfly_connection.cc:522] Socket error system:110 Connection timed out
W20230616 16:25:13.794234  2503 dragonfly_connection.cc:522] Socket error system:110 Connection timed out
W20230616 16:25:13.794246  2568 dragonfly_connection.cc:522] Socket error system:110 Connection timed out
W20230616 16:25:13.794250  2527 dragonfly_connection.cc:522] Socket error system:110 Connection timed out
W20230616 16:25:13.794231  2545 dragonfly_connection.cc:522] Socket error system:110 Connection timed out
W20230616 16:25:13.794240  2595 dragonfly_connection.cc:522] Socket error system:110 Connection timed out
W20230616 16:25:13.794232  2618 dragonfly_connection.cc:522] Socket error system:110 Connection timed out
W20230616 16:25:13.794232  2323 dragonfly_connection.cc:522] Socket error system:110 Connection timed out
W20230616 16:25:13.794881  2608 dragonfly_connection.cc:522] Socket error system:110 Connection timed out

**Comment by romange** [comment] 2023-06-19 04:03
@kissingtiger  it's not a bug by itself. TCP connections can time out. Are you using replication?

**Comment by kissingtiger** [comment] 2023-06-19 04:44
Yes, this error is the log of the replication instance

**Comment by romange** [comment] 2023-07-13 07:44
@kissingtiger can you please tell me what the error looks like in the recent version?

**Comment by Abhra303** [comment] 2023-10-17 05:08
Hi @kissingtiger, does the error still persist? If not, I will close the issue.

**Comment by thecodeassassin** [comment] 2024-07-24 23:26
Hello, we are also having this issue.

We are currently not using replication but we do want to use it in the future.  We are using ioredis to connect to Dragonfly. Is there any ioredis tweaking that we can do to get rid of these errors?

**Comment by romange** [comment] 2024-07-25 06:02
You need to properly close your client connections so that the server will know they are closed.

**Closed by romange** 2024-07-25 06:02 UTC
Labels: bug
