### ISSUE TITLE
Poor performance of hgetall with multiple fieldvalue

### ISSUE THREAD

**Issue by 0xManjeet** [dragonflydb/dragonfly#1907] opened 2023-09-20 18:11 UTC
**Describe the bug**
`Hgetall` is much slower in dragonfly compared to redis.

**To Reproduce**
1. Hset with multiple fieldvalues in 100 keys.
2. Now Hgetall all the 100 keys, and compare the timing with redis.
3. On my local system (ryzen 5500u), this takes 45ms with dragonflydb and 1.6ms with redis.

**Expected behavior**
Dragonfly should be at least as fast as redis.

**Environment (please complete the following information):**
 - OS: Manjaro
 - Kernel: Linux Raxy-7 6.1.19-1-MANJARO #1 SMP PREEMPT_DYNAMIC Mon Mar 13 12:59:35 UTC 2023 x86_64 GNU/Linux
 - Containerized?: tried with both native and docker
 - Dragonfly Version: 1.10.0

**Reproducible Code Snippet**
```
package main

import (
	"context"
	"crypto/rand"
	"fmt"
	"time"

	"github.com/redis/rueidis"
)

type RedisClient struct {
	rueidis.Client
}

func NewRedisClient() (*RedisClient, error) {
	client, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress:  []string{"0.0.0.0:6379"},
		DisableCache: true,
	})

	if err != nil {
		return nil, err
	}
	return &RedisClient{client}, nil
}

func main() {
	client, err := NewRedisClient()
	if err != nil {
		panic(err)
	}
	defer client.Close()
	client.Do(context.Background(), client.B().Flushall().Build())

	// hset with 100 keys
	cmds := rueidis.Commands{}
	t1 := time.Now()
	val := make([]byte, 1000)
	rand.Read(val)
	for i := 0; i < 100; i++ {
		cmds = append(cmds, client.B().Hset().Key(fmt.Sprintf("key_%d", i)).FieldValue().FieldValue("valx", "yug478y").FieldValue("hbhy", "uhnu").FieldValue("val", string(val)).Build())
	}
	client.DoMulti(context.Background(), cmds...)
	fmt.Println("took ", time.Since(t1))

	// now let's read all the keys
	cmds = rueidis.Commands{}
	for i := 0; i < 100; i++ {
		cmds = append(cmds, client.B().Hgetall().Key(fmt.Sprintf("key_%d", i)).Build())
	}

	// --------
	t1 = time.Now()
	client.DoMulti(context.Background(), cmds...)
	fmt.Println("took ", time.Since(t1))
	// redis: 1ms
	// dragonflydb: 49ms
	// ----------
}

```

**Comment by chakaz** [comment] 2023-09-20 19:14
Hi @0xManjeet, thanks for filing this issue!
May I kindly ask for you to elaborate on your use case? What are you using Dragonfly (and/or Redis) for, size of data and typical load?
Regarding your issue: Dragonfly is multi-threaded with a shared-nothing design. That means that keys are uniquely owned by shard threads, and are not shared between threads.
So by issuing a command that inspects many keys at once, coordination between all threads must be done, which slows down response time. I'm not sure if this is under load, but I can certainly see how a loaded system would cause a transaction queue to grow, increasing latency as a result.

Do the keys that you use with `HGETALL` have some common pattern? In other words, are the same keys usually accessed together?
If so, you could "group" keys which are accessed together (for example all keys belonging to some user) with [hashtags](https://redis.io/docs/reference/cluster-spec/#hash-tags). This will guarantee that keys using the same hashtag will also be using the same thread

Then run Dragonfly with emulated cluster mode, by adding `--cluster_mode=emulated` to the Dragonfly command line.

Does that help in any way?

**Comment by royjacobson** [comment] 2023-09-20 20:37
@chakaz, `HGETALL` is only accessing one key at a time, I think everything is on the same shard.

**Comment by romange** [comment] 2023-09-21 05:23
@royjacobson I am surprised that you out of all people have not suspected the root cause (hint: 49ms latency). 
Nothing in Dragonfly server side can cause such huge latency. And indeed, with `dragonfly --tcp_nodelay`:
```
took  2.380674ms
took  2.286614ms
```

**Comment by chakaz** [comment] 2023-09-21 06:21
:facepalm: my bad!

**Comment by romange** [comment] 2023-09-21 16:02
what do you mean by key size? is it a hmap length or a size of each hset length? 
can you provide your example?

**Comment by 0xManjeet** [comment] 2023-09-21 16:44
> what do you mean by key size? is it a hmap length or a size of each hset length? can you provide your example? @0xManjeet

I meant the number of keys.
```
for i := 0; i < 10_000; i++ {
		cmds = append(cmds, client.B().Hset().Key(fmt.Sprintf("key_%d", i)).FieldValue().FieldValue("valx", "yug478y").FieldValue("hbhy", "uhnu").FieldValue("val", string(val)).Build())
	}
	client.DoMulti(context.Background(), cmds...)
	fmt.Println("took ", time.Since(t1))

	// now let's read all the keys
	cmds = rueidis.Commands{}
	for i := 0; i < 10_000; i++ {
		cmds = append(cmds, client.B().Hgetall().Key(fmt.Sprintf("key_%d", i)).Build())
	}
```

**Comment by romange** [comment] 2023-09-21 17:49
Please use `--pipeline_squash=2` for that @0xManjeet .

**Comment by dranikpg** [comment] 2023-09-26 07:08
Right now there is not much we can do about this issue - I hope using `--pipeline_squash` will improve your experience. For heavy reads, multiple clients should generally be used.

We'll continue improving our pipeline performance, but for now I'll close this issue. Please reopen it in case of any further inquiries

**Closed by dranikpg** 2023-09-26 07:08 UTC
Labels: bug
