### ISSUE TITLE
Dragonfly instances consume a relatively high amount of memory when running

### ISSUE THREAD

**Issue by kissingtiger** [dragonflydb/dragonfly#1710] opened 2023-08-17 14:55 UTC
version：df-v1.6.2
The host memory occupied by the Dragonfly instance during operation far exceeds the instance storage memory。
# Memory
used_memory:137367770528
**used_memory_human:127.93GiB**
used_memory_peak:227734733872
comitted_memory:-1272392216000
used_memory_rss:296642269184
**used_memory_rss_human:276.27GiB**

<img width="962" alt="image" src="https://github.com/dragonflydb/dragonfly/assets/18210209/83c5c66a-760b-4300-b751-1bfdb238434c">

**Comment by kissingtiger** [comment] 2023-08-17 15:04
--- End mimalloc statistics, took 6091us ---
total reserved: 2503377152, comitted: 2502906624, used: 1356373192

# Memory
used_memory:141207660016
used_memory_human:131.51GiB
used_memory_peak:227734733872
comitted_memory:-1271625051584
used_memory_rss:298913763328
used_memory_rss_human:278.38GiB
object_used_memory:137980392304
table_used_memory:4349803568
num_buckets:65560320
num_entries:47016611
inline_keys:1
strval_bytes:81762003648
updateval_amount:119534758144
listpack_blobs:279463
listpack_bytes:82484440
small_string_bytes:44795564752
pipeline_cache_bytes:215785488
maxmemory:375809638400
maxmemory_human:350.00GiB
cache_mode:cache

**Comment by kissingtiger** [comment] 2023-08-17 15:16
___ Begin mimalloc statistics ___
heap stats:    peak      total      freed    current       unit      count   
  reserved:  333.7 GiB 3714.6 GiB 3420.9 GiB  293.6 GiB                        
 committed:  303.4 GiB89254.8 GiB90438.8 GiB-1184.0 GiB                        ok
     reset:      0          0          0          0                            ok
   touched:    1.0 GiB    2.1 GiB 7630.0 GiB-7627.9 GiB                        ok
  segments:   26.6 Ki    34.0 Ki    25.0 Ki     9.0 Ki                         not all freed!
-abandoned:      0          0          0          0                            ok
   -cached:      0          0          0          0                            ok
     pages:      0          0       51.3 Mi   -51.3 Mi                         ok
-abandoned:      0          0          0          0                            ok
 -extended:      0    
 -noretire:      0    
     mmaps:      0    
   commits:   44.1 Mi 
   threads:    104        104          0        104                            not all freed!
  searches:     0.0 avg
numa nodes:       2
   elapsed: 1422028.859 s
   process: user: 2419118.309 s, system: 2954565.498 s, faults: 224, rss: 304.1 GiB, commit: 303.4 GiB

Arena statistics from thread:0
Count BlockSize Reserved Committed Used
1 8 65152 65152 28752
1 16 65152 65152 15552
2 16 65152 65152 26736
1 24576 516096 516096 466944
1 384 64896 64896 33024
1 32 65152 65152 32256
1 1792 64512 64512 34048
1 16 65152 65152 9600
2 32 65152 65152 14752
2 16 65152 65152 21776
1 8 65152 65152 19912
1 8 65152 65152 32088
4 64 65152 65152 26368
3 48 65136 65136 18384
.........
1 16 65152 65152 24208
1 224 64960 64960 12768
1 8 65152 65152 22168
2 8 65152 65152 21536
1 8 65152 65152 36240
1 32 65152 65152 44288
1 32 65152 65152 46272
1 32 65152 65152 34816
1 8 65152 65152 30016
1 8 65152 65152 27760
3 16 65152 65152 18976
1 16 65152 65152 8512
2 48 65136 65136 21504
1 32 65152 65152 35808
1 32 65152 65152 47264
1 8 65152 65152 19552
1 8 65152 65152 18560
4 16 65152 65152 16992
1 8 65152 65152 24152
--- End mimalloc statistics, took 6350us ---
total reserved: 2515962368, comitted: 2515123200, used: 1367366264

**Comment by kissingtiger** [comment] 2023-08-17 15:31
@romange Can you see the content of these two files normally?
https://alice-image.oss-cn-hongkong.aliyuncs.com/info_all.txt
https://alice-image.oss-cn-hongkong.aliyuncs.com/memory_malloc-stats.txt

**Comment by romange** [comment] 2023-08-17 15:38
Yes, this will do 😊

**Comment by royjacobson** [comment] 2023-08-17 16:40
Looks like really bad memory fragmentation. I sorted by amount of memory wasted and the largest contributors are buckets where only one allocation is still active:

![image](https://github.com/dragonflydb/dragonfly/assets/5706313/8810c017-13d2-45aa-80b4-a5cf0ab28e67)

Keep in mind there are 104 (!) threads running so 5.06MiB is 0.5GiB in the total memory consumption.
Also looks like there are MANY attempts at running de-fragmentation routine but no actual de-fragmentation is going on:

```
defrag_attempt_total:75664040156
defrag_realloc_total:0
defrag_task_invocation_total:192465464
```

**Comment by kissingtiger** [comment] 2023-08-17 16:49
@royjacobson @romange Is there anything that can be optimized? This is our production environment.

**Comment by romange** [comment] 2023-08-17 17:07
@kissingtiger nothing immediate I can think of. I will take a deeper look next week

**Comment by kissingtiger** [comment] 2023-08-17 17:10
@romange Waiting for your good news, thank you very much

**Comment by romange** [comment] 2023-08-17 17:27
Remind me how many threads/cpus are being used?

**Comment by romange** [comment] 2023-08-17 17:50
For the reference I attached the linked files. 

[memory_malloc-stats.txt](https://github.com/dragonflydb/dragonfly/files/12372238/memory_malloc-stats.txt)
[info_all.txt](https://github.com/dragonflydb/dragonfly/files/12372239/info_all.txt)

**Comment by romange** [comment] 2023-08-17 17:59
@royjacobson  I can confirm that 45% are lost due to fragmentation. 
![image](https://github.com/dragonflydb/dragonfly/assets/3674760/2c5bee61-2b36-403a-9ea5-903eedfdb5a0)

**Comment by kissingtiger** [comment] 2023-08-18 02:45
@romange This is dragonfly.conf ,The physical machine node CPU is 104 cores。
--pidfile=/data/dragonfly/run/dragonfly.pid
--log_dir=/data/dragonfly/logs
--dir=/data/dragonfly/data
--version_check=true
--cache_mode=true
--dbnum=16
--bind=0.0.0.0
--port=6379
--maxmemory=350g
--keys_output_limit=12288
--logtostderr=false

**Comment by kissingtiger** [comment] 2023-08-18 02:49
@romange @royjacobson I have 5 Dragonfly instances in my production environment that are all of the same version (version="df v1.6.2") and have the same issue. I am not sure if there will be an OOM issue. Please help analyze the solution as soon as possible，thank you very much.

**Comment by kissingtiger** [comment] 2023-08-20 17:12
Excuse me, does the memory fragmentation rate support manual recycling? Just now, the memory usage rate of the virtual machine has reached 95%, and I am worried that the Dragonfly service may experience OOM or exit abnormally.

**Comment by royjacobson** [comment] 2023-08-20 18:14
> 

You could do manual copy-delete-copy-delete operations in a script. I haven't tested it, so I can't be sure, but it sounds reasonably helpful. Restarting Dragonfly should also temporarily relieve the memory pressure, but it's definitely not an ideal way to solve it..

**Comment by kissingtiger** [comment] 2023-08-21 02:38
@royjacobson Okay, although this issue is very important to us, we can only wait for you to fix it first. We look forward to it very much,thanks.

**Comment by kissingtiger** [comment] 2023-08-21 05:49
@royjacobson @romange  It's quite painful, triggering OOM.
Out of memory: Killed process 1559583 (dragonfly) total-vm:418736372kB, anon-rss:385396272kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:780336kB oom_score_adj:0

**Comment by romange** [comment] 2023-08-21 08:04
@kissingtiger  for now you can try recreating your database using a client-side python script.
it should run a continuous scan operation `SCAN... type hash` that goes over all hashes and reads a number of keys, 
then it uses `WATCH`, `DUMP`, `MULTI` `RESTORE` `EXEC` sequences to dump/restore each hash atomically.
we have not tried doing this though
https://redis.io/docs/interact/transactions/#watch-explained
https://www.dragonflydb.io/docs/command-reference/generic/dump
https://www.dragonflydb.io/docs/command-reference/generic/restore

I suggest testing it on a test instance aside first.

**Comment by romange** [comment] 2023-08-21 08:16
I can confirm I performed this sequence on a toy database and it works.

**Comment by romange** [comment] 2023-08-21 09:09
@dranikpg  created this script: https://gist.github.com/dranikpg/b9d19f1555d050f2f07a07b2d7d3bcaa 
but it does not preserve TTLs. You need to modify it if your hashes have TTLs.

**Comment by kissingtiger** [comment] 2023-08-21 12:15
@romange https://gist.github.com/dranikpg/b9d19f1555d050f2f07a07b2d7d3bcaa
Can this script be run directly?

**Comment by kissingtiger** [comment] 2023-08-21 12:50
@dranikpg Okay, I'll give it a try. Thank you.
After the OOM restarts, the memory goes up again
<img width="1113" alt="image" src="https://github.com/dragonflydb/dragonfly/assets/18210209/cd1d2e78-b0a8-4737-8c76-afbbd8f6a4a7">

**Comment by kissingtiger** [comment] 2023-08-22 08:20
https://gist.github.com/dranikpg/b9d19f1555d050f2f07a07b2d7d3bcaa
@dranikpg Hello, may I ask how to modify this script to support password verification, as my Dragonfly instance has a password set.

**Comment by dranikpg** [comment] 2023-08-22 09:25
@kissingtiger 

Sure, updated the revision (7th). Use the `--password` flag to provide it

**Comment by kissingtiger** [comment] 2023-08-23 06:24
@dranikpg Hello, I executed this script and it has some effects, but I found that there is relatively little memory reclamation.
used_memory_human:**202.80GiB**
used_memory_rss_human:**246.09GiB**

**Comment by romange** [comment] 2023-08-24 10:08
> @kissingtiger I suggest running `memory malloc-stats` right before running the script and right after running the script and send us here both outputs.

@kissingtiger  we need to get `memory malloc-stats` before running the script and right after. Will you be able to do it?

**Comment by kissingtiger** [comment] 2023-08-24 11:13
@romange 
I tried it, but running this script has an impact on the business, and the delay will increase. Now, due to the restart of the instance OOM, the memory fragmentation rate is not high.

**Comment by romange** [comment] 2023-08-24 12:33
ok, please follow this exact procedure  when the instance memory will grow and you will need to fix it anyways.
please do not forget to provide `memory malloc-stats` before and after. otherwise, we won't be able to issue a permanent fix for the issue.

**Comment by kissingtiger** [comment] 2023-08-25 03:22
@romange Is the memory fragmentation rate calculation formula correct?
memory malloc-stats output:
--- End mimalloc statistics, took 10379us ---
total reserved: 3928794544, comitted: 3927979440, used: 3482482024

Memory fragmentation rate = （comitted-used）/ comitted

**Comment by romange** [comment] 2023-08-25 04:07
Yes

**Comment by kissingtiger** [comment] 2023-08-28 08:57
@romange @dranikpg 
Before executing the script：
<img width="738" alt="image" src="https://github.com/dragonflydb/dragonfly/assets/18210209/cc2da784-d3d3-44d9-85bc-549c1e0f7a6d">
Executing commands without taking any action：
<img width="1245" alt="image" src="https://github.com/dragonflydb/dragonfly/assets/18210209/17f0a132-4e64-43c6-a676-46734acdfe96">

**Comment by dranikpg** [comment] 2023-08-28 09:34
Strange, it shows `recycled in total: 0`. It didn't find any hashes on your db=0 🤔 

By the way, we now have built-in support for hash defragmentation on the main branch. It should be available on the latest weekly ubuntu docker image. It should work more reliably, because it explicitly checks for memory under-utilization

**Comment by kissingtiger** [comment] 2023-08-28 10:57
@dranikpg Yes, it's quite strange, but my data is all on db0.
By the way, please let me know how long it will take for the release version to support memory fragmentation recycling. I'm worried that we'll have to OOM again

**Comment by kissingtiger** [comment] 2023-08-29 02:51
@romange Added this parameter(--type=hash), but the result is still the same
<img width="1511" alt="image" src="https://github.com/dragonflydb/dragonfly/assets/18210209/0b900232-6e08-4399-a433-01ba401211d5">

**Comment by romange** [comment] 2023-08-29 02:54
You have not taken.the.version I sent.
Can you run 'reds-cli  scan 0 type hash''?

**Comment by kissingtiger** [comment] 2023-08-29 03:06
1) "0"
2) (empty array)

**Comment by dranikpg** [comment] 2023-08-29 20:42
> Can you run 'reds-cli scan 0 type hash''?

> "0"
> (empty array)

It means the database you're connecting to with redis-cli doesn't have any values of the type 'hash' 🤔

**Comment by romange** [comment] 2023-08-29 21:02
Yes, we talked offline. He run the script and this command on another instance so the whole experiment was broken.

**Comment by kissingtiger** [comment] 2023-09-18 02:30
Hello, has the latest version fixed this issue?

**Comment by romange** [comment] 2023-09-18 03:04
yes, it should have

**Comment by chakaz** [comment] 2023-09-19 07:11
Please let us know if it did not!
I'm optimistically closing this issue for now.

**Closed by chakaz** 2023-09-19 07:11 UTC
Labels: bug
