### ISSUE TITLE
Datagrip support

### ISSUE THREAD

**Issue by glad2os** [dragonflydb/dragonfly#1707] opened 2023-08-16 15:30 UTC
**Describe the bug**
Clicking in the DataGrip to see what's inside the hash tables printing `ERR wrong number of arguments for 'hrandfield' command`

 
`java.sql.SQLException: redis.clients.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'hrandfield' command at jdbc.client.impl.RedisClientBase.sqlWrap(RedisClientBase.java:80) at jdbc.client.impl.RedisClientBase.execute(RedisClientBase.java:27) at jdbc.RedisStatement.executeImpl(RedisStatement.java:37) at jdbc.RedisStatement.execute(RedisStatement.java:122) in RemoteStatementImpl.execute(RemoteStatementImpl.java:79) Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'hrandfield' command at redis.clients.jedis.Protocol.processError(Protocol.java:96) at redis.clients.jedis.Protocol.process(Protocol.java:137) at redis.clients.jedis.Protocol.read(Protocol.java:192) at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316) at redis.clients.jedis.Connection.getOne(Connection.java:298) at redis.clients.jedis.Jedis.sendCommand(Jedis.java:9482) at jdbc.client.impl.standalone.RedisJedisClient.executeImpl(RedisJedisClient.java:42) at jdbc.client.impl.RedisClientBase.execute(RedisClientBase.java:34) at jdbc.client.impl.RedisClientBase.execute(RedisClientBase.java:24) at jdbc.RedisStatement.executeImpl(RedisStatement.java:37) at jdbc.RedisStatement.execute(RedisStatement.java:122) in RemoteStatementImpl.execute(RemoteStatementImpl.java:79) ... 3 more `
 

**To Reproduce**
```
const redisClient = redis.createClient(
    {
        url: 'redis://localhost:6379/',
    }
);

players.push({id: socket.id, mmr: mmr, username: username, type: type});
await redisClient.hSet(`Lobby:${lobbyID}`, "Players", JSON.stringify(players));
```

**Expected behavior**
Using Redis image at the Datagrip (Jetbrains) I could see the data inside the hash tables. Probably due to protocol or something else using Dragonflydb, I can not see the data inside. All data has been proceeded correctly (not the problem of writing or reading)

**Screenshots**

**Environment (please complete the following information):**
 - OS: WSL 2, Ubuntu
 - Kernel: # Command: `uname -a`
 - Containerized?: Docker compose
 - Dragonfly Version: [e.g. 0.3.0]]: image: docker.dragonflydb.io/dragonflydb/dragonfly

**Reproducible Code Snippet**
```
# Minimal code snippet to reproduce this bug
```

**Additional context**

**Comment by romange** [comment] 2023-08-16 20:42
duplicate of https://github.com/dragonflydb/dragonfly/issues/858

**Closed** 2023-09-06 09:04 UTC
Labels: bug, help wanted, good first issue

**Comment by theyueli** [comment] 2023-09-07 07:53
hi @glad2os,  could you try your use case again to see if we have resolved your particular case? Thanks!

**Comment by glad2os** [comment] 2023-09-08 20:31
@theyueli @romange Hello! I have got `ERR wrong number of arguments for 'hrandfield' command
Details`

```
[2023-09-08 16:29:54] Connected
0> SELECT 0
[2023-09-08 16:29:54] completed in 3 ms
0> HRANDFIELD GameWS:QCjo_J4ea8lHMhSsAAAD 501 WITHVALUES
[2023-09-08 16:29:54] ERR wrong number of arguments for 'hrandfield' command

 
```

Using

```
  dragonflydb:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
```

**Comment by theyueli** [comment] 2023-09-08 21:12
hi @glad2os , 

sorry for the confusion, the docker image uses a released version. The change that supports HRANDFIELD has not been released, but is available in the upstream code repository. 

@romange could we create a docker image of the upstream version? Or if @glad2os you can't wait, you could also build a local version using the latest source code...

**Comment by theyueli** [comment] 2023-09-27 08:38
hello again @glad2os , this change should now be available in our latest release. Could you have another try to see if this works for you? Thanks!
