### ISSUE TITLE
test_cluster_migration_cancel assertion failure

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#3484] opened 2024-08-09 06:53 UTC
see: https://github.com/dragonflydb/dragonfly/actions/runs/10309432284/job/28539074826

```
>       assert await nodes[1].client.dbsize() == 0
E       assert 1 == 0
```

**Comment by BorysTheDev** [comment] 2024-09-09 11:41
I can't reproduce it anymore, maybe it was fixed by #3653.

**Comment by BorysTheDev** [comment] 2024-09-09 13:28
still exist

**Comment by kostasrim** [comment] 2024-09-09 13:38
Recent failure https://github.com/dragonflydb/dragonfly/actions/runs/10772716043

**Closed** 2024-09-10 11:42 UTC
Labels: bug, failing-test
