### ISSUE TITLE
`DflyShardReplica::ExecuteTx` crashes 

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#3930] opened 2024-10-15 11:04 UTC
failing test test_cluster_native_client

```
30103➜    @           0x4ab59d  __assert_fail

30103➜    @           0x438bb3  boost::intrusive::detail::destructor_impl<>()

30103➜    @           0x432b18  boost::intrusive::slist_member_hook<>::~slist_member_hook()

30103➜    @           0x432b68  util::fb2::detail::Waiter::~Waiter()

30103➜    @           0xe8b0a3  util::fb2::CondVarAny::wait<>()

30103➜    @           0xe8ace4  _ZN4util3fb210CondVarAny4waitISt11unique_lockINS0_5MutexEEZNS0_7Barrier4WaitEvEUlvE_EEvRT_T0_

30103➜    @           0xe8aca3  _ZN4util3fb27CondVar4waitIZNS0_7Barrier4WaitEvEUlvE_EEvRSt11unique_lockINS0_5MutexEET_

30103➜    @           0xe8aba8  util::fb2::Barrier::Wait()

30103➜    @           0xadd1e4  dfly::DflyShardReplica::ExecuteTx()
```
see 
https://github.com/dragonflydb/dragonfly/actions/runs/11343555702/job/31546353995?pr=3924#step:12:818

for more details

**Comment by BorysTheDev** [comment] 2024-10-17 11:18
To my mind, the problem is in void CondVarAny::wait(LockType& lt)
variable detail::Waiter waiter is removed but isn't removed from wait_queue_

**Comment by BorysTheDev** [comment] 2024-10-17 14:27
I think I found data race in the Barrier class:
Barrier.wait();
Barrier.wait();

The second wait() creates a data race in the case if during the first one one thread execute lk.unlock();  // no pessimization
    cond_.notify_all();

**Comment by BorysTheDev** [comment] 2024-10-19 19:55
@romange I think I have found quite a good solution https://github.com/romange/helio/pull/324

**Comment by kostasrim** [comment] 2024-10-21 13:37
> I think I found data race in the Barrier class:
> 
> ```
> Barrier.wait();
> Barrier.wait();
> ```
> 
> The second wait() creates a data race in the case if during the first one wait() one thread execute
> 
> ```
> lk.unlock();
> cond_.notify_all(); // but don't leave it and use iterate wait_list_ in the wait_queue_ without lock
> ```
> 
> the second thread finishes wait() and start the second wait() this second wait update wait_list_ in the wait_queue_ under the lock, but we still iterating this wait_list in the first thread without the lock
> 
> @romange I think if I move cond_.notify_all(); before lk.unlock(); it should fix the problem, what do you think?

I am not sure I understand this. Based on what you write the problem seems to be that the first thread iterates over the `WaitQueue` while the second thread wakes up from the first `Wait()` an enters the `second Wait`. But, we have this in the critical section of the Barrier:
```
  158 bool Barrier::Wait() {                                                                             
  159   unique_lock lk{mtx_};
  160   const size_t cycle = cycle_;
  161   if (0 == --current_) {
  162     ++cycle_;
  163     current_ = initial_;
  164     lk.unlock();  // no pessimization
  165     cond_.notify_all();                                                                        
  166     return true;                                                                                 
  167   }                                                                               
  168                                                                                
  169   cond_.wait(                                                                 
  170       lk, [&] { return (cycle != cycle_) || (cycle_ == std::numeric_limits<std::size_t>::max()); });
  171   return false;                                               
  172 } 

  ```
  Now when that second thread calls `Wait()` for the second time, it won't trigger `if(0 == --current_)` since thread 1 set `current_ = initial)` and `initial_` should be `>1` (otherwise there is only one shard and `Wait()` waits on itself so it does not have to block).
  
  What am I missing here?

**Comment by BorysTheDev** [comment] 2024-10-21 15:57
modifying wait_queue from 2 threads without synchronization

**Comment by BorysTheDev** [comment] 2024-10-21 20:21
was fixed by https://github.com/romange/helio/pull/324

**Closed by BorysTheDev** 2024-10-21 20:21 UTC
Labels: bug, failing-test

**Comment by kostasrim** [comment] 2024-10-22 07:10
> modifying wait_queue from 2 threads without synchronization

right right because of the `wait` below
