### ISSUE TITLE
JSON.MERGE still missing for the json commands

### ISSUE THREAD

**Issue by admtech** [dragonflydb/dragonfly#1572] opened 2023-07-19 12:02 UTC
JSON.MERGE still missing for the json commands. See: https://redis.io/commands/json.merge/

**Comment by romange** [comment] 2023-07-19 12:06
do you use it directly or via some framework?

**Comment by admtech** [comment] 2023-07-19 12:14
Both. Once with the "predis" PHP Redis library and also directly when I want to change content manually. Without JSON.MERGE, you have to load the existing json content first and then merge it with the new one via the programming language. This is an unnecessary step.

**Comment by iko1** [comment] 2023-07-22 08:18
@romange, can you assign it to me?

**Comment by 0xArdi-N** [comment] 2023-10-28 10:53
Hi, seems a lot of issue needed help,  can I pick this want as a my first contribution?

**Comment by chakaz** [comment] 2023-10-29 02:28
Hi @0xArdi-N, feel free to :)
We do mark easier tasks with the label https://github.com/dragonflydb/dragonfly/labels/good%20first%20issue, but perhaps this one is not too hard too

**Comment by romange** [comment] 2024-06-11 03:16
Duplicate of #2960

**Closed by romange** 2024-06-11 03:16 UTC
Labels: enhancement, help wanted, hacktoberfest
