### ISSUE TITLE
test_replicate_disconnect_redis_cluster

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#3848] opened 2024-10-01 16:06 UTC
Failed:

```
2024-10-01T16:04:06.6448986Z         capture = await seeder.capture()
2024-10-01T16:04:06.6449855Z >       assert await seeder.compare(capture, replica.port)
2024-10-01T16:04:06.6450884Z [1m[31mE       assert False[0m
```

https://github.com/dragonflydb/dragonfly/actions/runs/11128041149

**Comment by adiholden** [comment] 2024-10-06 07:43
duplicate of https://github.com/dragonflydb/dragonfly/issues/3622

**Closed by adiholden** 2024-10-06 07:43 UTC
Labels: bug, failing-test
