### ISSUE TITLE
cluster_fuzzymigration test failure

### ISSUE THREAD

**Issue by chakaz** [dragonflydb/dragonfly#3131] opened 2024-06-05 05:59 UTC
We saw a failure in regtests:
https://github.com/dragonflydb/dragonfly/actions/runs/9369475602/job/25794091021#step:6:514

@BorysTheDev says it's a new failure

**Comment by BorysTheDev** [comment] 2024-06-05 17:13
It looks like the issue is happen during migration

**Comment by BorysTheDev** [comment] 2024-06-13 13:25
should be fixed by #3171

**Closed** 2024-06-20 09:37 UTC
