### ISSUE TITLE
Need to configure ACLs - users and passwords with keys 

### ISSUE THREAD

**Issue by dgaastra** [dragonflydb/dragonfly#1416] opened 2023-06-15 13:24 UTC
**Did you search GitHub Issues and GitHub Discussions First?**
Could not find anything here.

**Is your feature request related to a problem? Please describe.**
Need to configure ACLs - users and passwords with keys 
Would like redis feature to work: aclfile /etc/redis/redis-users.acl

**Describe the solution you'd like**
- from Redis -
```
- # Using an external ACL file
#
# Instead of configuring users here in this file, it is possible to use
# a stand-alone file just listing users. The two methods cannot be mixed:
# if you configure users here and at the same time you activate the external
# ACL file, the server will refuse to start.
#
# The format of the external ACL user file is exactly the same as the
# format that is used inside redis.conf to describe users.
#
#aclfile /etc/redis/users.acl
```

**Describe alternatives you've considered**
Redis works - need this in order to deploy DragonFLyDB

**Additional context**
This is for multiple simultaneous PHP  environments with separated access.

Thanks
Dennis

**Comment by romange** [comment] 2023-06-16 04:45
Duplicate of #447 . Please vote there

**Closed by romange** 2023-06-16 04:45 UTC

**Comment by dgaastra** [comment] 2023-06-16 09:21
Please note that every user needs segregated access, even if we host only one client per VM - for hacker proofing DEV from STG from LIVE.
