### ISSUE TITLE
Server crash on Flushall command when using transaction block 

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#601] opened 2022-12-26 08:09 UTC
1. multi
 2. flushall
 3. exec

**Comment by romange** [comment] 2023-01-07 06:55
is it duplicate of https://github.com/dragonflydb/dragonfly/issues/641 ?

**Comment by adiholden** [comment] 2023-01-08 07:38
yes @romange you are right I will close this one

**Closed** 2023-01-08 07:39 UTC
Labels: bug
