### ISSUE TITLE
RESTORE ... ABSTTL is not working as expected

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#837] opened 2023-02-21 10:26 UTC
**Describe the bug**
`ABSTTL` option should treat `<ttl>` argument as absolute time. 

**To Reproduce**
```
> RESTORE key 1776974658 "\x0e\x01\x11\x11\x00\x00\x00\x0e\x00\x00\x00\x03\x00\x00\xf2\x02\xf3\x02\xf4\xff\t\x00\xfa\x81\x98P\x85\xf8\xd9\xed" ABSTTL
OK
> type key
none
```

**Expected behavior**
Th blob should be restored as a list, i.e. `type key` should return `list`.

**Comment by adiholden** [comment] 2024-06-17 05:44
@chakaz please check cluster migration tests , we are using restore command so we should have seen  this bug in the tests

**Comment by chakaz** [comment] 2024-06-17 05:52
@adiholden nice catch! I don't think we have any cluster migration tests which use TTL, so I'll make sure to add some

**Comment by BagritsevichStepan** [comment] 2024-06-19 19:12
The problem is that the specified time (`1776974658`) is too short. I also made this mistake by calling `TIME` first, increased the received time by some big number, and then called `RESTORE ABSTTL` with the calculated time.

The problem is that `TIME` returns the time in **seconds**, and the `RESTORE` command requires ttl in **milliseconds**. So the time received from `TIME` command must be multiplied by 1000 first. 

The specified unix time 1776974658 in milliseconds corresponds to _Wed Jan 21 1970 13:36:14_.

Example of how I tested it:
```bash
127.0.0.1:6379> lpush list "hello"
(integer) 1
127.0.0.1:6379> rpush list "world"
(integer) 2
127.0.0.1:6379> dump list
"\x0e\x01\x19\x19\x00\x00\x00\x11\x00\x00\x00\x02\x00\x00\x05hello\a\x05world\xff\t\x00\xa0\x85\xec\x96\xab\xc4\xdak"
127.0.0.1:6379> flushall
OK
127.0.0.1:6379> time
1) (integer) 1718824024
2) (integer) 229294
127.0.0.1:6379> restore anotherlist 1718824094000 "\x0e\x01\x19\x19\x00\x00\x00\x11\x00\x00\x00\x02\x00\x00\x05hello\a\x05world\xff\t\x00\xa0\x85\xec\x96\xab\xc4\xdak" ABSTTL
OK
127.0.0.1:6379> type anotherlist
list
127.0.0.1:6379> llen anotherlist
(integer) 2
127.0.0.1:6379> ttl anotherlist
(integer) 28
```

**Comment by BagritsevichStepan** [comment] 2024-06-19 19:12
In `OnRestore` we have if-statement `if (restore_args.Expired())`. If it is true, we don't add the key to the storage and return true to the user.

I propose not just sending OK to the user, but printing a message that the specified time has already expired.

**Comment by chakaz** [comment] 2024-06-19 19:34
@BagritsevichStepan just to make sure I understand you, currently Dragonfly works as intended, but it's just confusing that `TIME` and `ABSTTL` work in different time units?

**Comment by chakaz** [comment] 2024-06-20 10:01
> I propose not just sending OK to the user, but printing a message that the specified time has already expired.

There could be valid cases for such restoration, I wouldn't add such prints at the moment.

I think we can just close this issue as working as intended :)
Unless we come up with a time machine to, maybe, change the spec of TIME, TTL, etc.

**Closed** 2024-06-20 19:24 UTC
Labels: bug, docs-fixit
