### ISSUE TITLE
Uncaught exception on rename dis

### ISSUE THREAD

**Issue by fernandomacho** [dragonflydb/dragonfly#3072] opened 2024-05-22 16:47 UTC
Dragonfly crash when try to rename tmp dump.

F20240522 02:32:26.647239 3603399 init.cc:83] Uncaught exception: filesystem error: cannot rename: No such file or directory [/var/lib/dragonfly/dump-2024-05-22T02:32:22-0000.dfs.tmp] [/var/lib/dragonfly/dump-2024-05-22T02:32:22-0000.dfs]

Yesterday my dragonfly crash when. try to rename dump file.

Evidently the /var/lib/draginfly directory exists and there is enough disk space.
After the crash dragonfly does not load the last saved snapshot.

My version is 1.18.1

Thanks

**Comment by romange** [comment] 2024-05-22 17:59
@BorysTheDev  can you please take a look?

**Comment by kostasrim** [comment] 2024-05-27 13:28
@BorysTheDev I suspect they used `CONFIG SET DBFILENAME` and tried to change the name dynamically. The rest of the chore should help to reproduce it

**Comment by fernandomacho** [comment] 2024-05-27 16:53
Hello, we save we manually run every hour at minute 0 with BGSAVE command (just without the DBFILENAME SET) and in the config flag file it is configured to save every hour 
`--snapshot_cron=0` */1 * * * 
--dbfilename=dump-{timestamp}
` 
The cron is redundant, but if you look at the time of the error it doesn't look like this. The error occurs at 02:32:22.

Never use CONFIG SET DBFILENAME

**Comment by BorysTheDev** [comment] 2024-05-27 17:05
@fernandomacho do I understand that you have 2 backup mechanisms with BGSAVE and the snapshot_cron save, and the crash is happened during  snapshot_cron save?
Also, could you clarify if there were other *.dfs.tmp files in the folder or any files with the modification timestamp near 2024-05-22T02:32:22

**Comment by fernandomacho** [comment] 2024-05-27 17:12
Hello, correct. 
It doesn't seem to be the snapshot because as you can see it should run every hour at 0 minutes. 
But the system cron doesn't run at the time of the crash either. 
I can't tell you what was in that directory when the error happened, but there certainly wasn't any backup, because when dragonfly restarted, in the logs it said that there was no backup and it booted empty.

**Comment by BorysTheDev** [comment] 2024-05-27 17:20
Please don't close it. Anycase, I want to prevent crashing if the snapshot fails and add error logs instead

**Comment by kostasrim** [comment] 2024-05-27 18:21
> But the system cron doesn't run at the time of the crash either.

We should verify this

**Comment by fernandomacho** [comment] 2024-05-28 18:31
Thanks!!

**Comment by BorysTheDev** [comment] 2024-05-29 09:20
@kostasrim I haven't found the reason for the issue, so I think we can close it until we get some additional info.

**Closed** 2024-05-29 12:23 UTC
Labels: bug, Next Up
